### ISSUE TITLE
Zig-Zag Rotations in Balanced BST Lecture

### ISSUE THREAD

**Issue by chloeslam** [emory-courses/dsa-java#102]
**Balanced BST Lecture**
-----
I tried drawing out the rotations for the left and right zig-zag conditions, but I can't understand how we can only perform rotations to get the zig-zag conditions to be balanced. Attached to this issue is a picture of my problem. Can someone please explain how the connectivity does not need to be rearranged?

![IMG_5B905BC6CBE6-1](https://user-images.githubusercontent.com/69940082/95524835-18c25500-0998-11eb-8aae-dd7aa779a48f.jpeg)

**Comment by jdchoi77** [comment]
@chloeslam after left-rotate on (1), the tree becomes left-linear as the top-left figure. then perform right-rotate on (3) would give the figure in the center.

**Comment by chloeslam** [comment]
So after the left-rotate on (1), (3) will no longer be connected to (1)? Because the figure in the center has (3) connected to (2) and no longer connected to (1), but I thought these only require rotations and no breaking of connectivity.

**Comment by chloeslam** [comment]
Oh nevermind, I understand it now!
