### ISSUE TITLE
[HW1]  won't return result

### ISSUE THREAD

**Issue by brendacano** [emory-courses/dsa-java#104]
[https://github.com/brendacano/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/hybrid/HybridSortHW.java](https://github.com/brendacano/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/hybrid/HybridSortHW.java)

I was debugging my code as well as placed printlns to check everything. The code is able to sort the array but for some reason right before it can return the result it will call sort again even though it isn't a recursive method. 

If the image helps, it shows that it got sorted displaying the final array. After checkpoint 5 it is supposed to return the result. But as you can see it goes back to checkpoint 1. I honestly have no idea what's happening. 
![2020-10-09](https://user-images.githubusercontent.com/69967655/95578615-2ad8dd80-0a02-11eb-9e3d-c9530568a217.png)

**Comment by Kaseyc27** [comment]
Remove any print statements?

**Comment by brendacano** [comment]
I removed the print statements when I committed and pushed the code.
