### ISSUE TITLE
[QZ4] A Minor Mistake In Quiz 4

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#109]
Sorry to interrupt, but I just found a minor mistake in quiz 4. I realized that Dr. Choi accidentally named "BalancedBinarySearchTreeQuiz"  as  "BalacnedBinarySearchTreeQuiz". I am actually quite worried about whether my code will run using Dr. Choi's packages if I named the java class differently. Thanks in advance!

**Comment by jdchoi77** [comment]
@HallOfSam thanks for letting me know; the typo has been fixed. Please feel free to fixed the typo in your package. Regardless, the name of the class should not matter for running.
