### ISSUE TITLE
[QZ0] How to open gradle/wrapper/....

### ISSUE THREAD

**Issue by ywu496** [emory-courses/dsa-java#11]
When trying to follow the setup instructions, I got lost at the following command:

"Open gradle/wrapper/gradle-wrapper.properties and make sure distributionUrl indicates the latest version of Gradle:"

I have already created a gradle project but don't know where to open the directory above(cmd or somewhere on IntelliJ?)

**Comment by lujiaying** [comment]
@ywu496 could you share some updates about this issue?

**Comment by ywu496** [comment]
Hi, thanks for helping out! I'm actually planning to go to your office hours for this. I've tried for hours trying to solve this sync failed error. I already have the Gradle downloaded(independently), but the sync failed error never goes away. When I open the "Build Tools" and select "Gradle", I could see that "gradle-wrapper.properties not found" error. I suppose it is either that Gradle is not installed properly or the directory is not set properly, which I tried but couldn't solve. 
![buhuo1](https://user-images.githubusercontent.com/69917863/91050740-19bc4480-e5ed-11ea-9b4c-2fda7ea0eb73.JPG)

**Comment by lujiaying** [comment]
> I suppose it is either that Gradle is not installed properly or the directory is not set properly, which I tried but couldn't solve.

Thanks for the detailed update. 
Yes, I agree with your speculation. Some students have encountered similar situations due to "sync issue". The sync process could be slow if the internet connection is not stable since it needs to download necessary support library such as `org.junit.test`. 

I would say, your actions are mostly correct. And you are welcome to drop by during office hours.

**Comment by ywu496** [comment]
Hi, I tried to join the office hour zoom session, but it says that it's a recurring meeting. Do we have office hours today at all?

**Comment by jdchoi77** [comment]
@ywu496 Please check the office hours on the syllabus: https://github.com/emory-courses/dsa-java/blob/master/docs/syllabus.md#office-hours

**Comment by ywu496** [comment]
I finally solved the problem by installing Gradle first and then re-installing IntelliJ.
