### ISSUE TITLE
[QZ3] Confusion on Grading comments

### ISSUE THREAD

**Issue by BaichenRong** [emory-courses/dsa-java#110]
Replace `#` in the title with the appropriate quiz number.
![image](https://user-images.githubusercontent.com/69851166/95779436-144bb400-0c98-11eb-8a37-cf9022e58657.png)
I am sorry I cannot understand what it said. Could Mr.Ma elaborate a little bit more in detail about why I get punished on comparing?

**Comment by marvinquiet** [comment]
Because you did not actually compare the run time speed for ascending/descending orders. What you drew in your plot are "comparisons" and "assignments".
