### ISSUE TITLE
[QZ#4] Testing

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#112]
Once you've created your balance() method, what is the instructor-approved way of testing it?

**Comment by lujiaying** [comment]
Not sure I understand the question. What does "instructor-approved" refer to?

**Comment by TFloyd1989** [comment]
Usually, there is a specific way to test quiz/hw files, like hybridsorttest for example. I was wondering for this assignment if there is a specific testing structure we must follow as we have done before? Or if we have to make up our own testing this time

**Comment by lujiaying** [comment]
Gotcha. I think I am not able to answer this question. Please wait for @jdchoi77 to respond. Or feel free to ask during class.

**Comment by brendacano** [comment]
[https://github.com/emory-courses/dsa-java/tree/master/src/test/java/edu/emory/cs/tree](https://github.com/emory-courses/dsa-java/tree/master/src/test/java/edu/emory/cs/tree)

look at his test classes in github

**Comment by lujiaying** [comment]
> https://github.com/emory-courses/dsa-java/tree/master/src/test/java/edu/emory/cs/tree
> 
> look at his test classes in github

I think these files are test cases for AVLTree, RedBlackTree.
