### ISSUE TITLE
[QZ#4] Are we assuming 3 is the root node?

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#113]
Replace `#` in the title with the appropriate quiz number.
Do we only need to take into account the 4 cases presented in the homework or do we need to also take into account whether the "3" node has a parent?

**Comment by lujiaying** [comment]
From my perspective, during the actual grading process, we would add more test cases.

**Comment by Shreya3554** [comment]
But I'm still not understanding how that works. After balancing the example cases, do we need to balance up the tree?

**Comment by lujiaying** [comment]
About the output tree, it is expected to be a balanced one. please also refer to https://github.com/emory-courses/dsa-java/issues/114

**Comment by Shreya3554** [comment]
Thank you! So is the tree that was drawn in @114 considered to be a correct output?

**Comment by lujiaying** [comment]
> Thank you! So is the tree that was drawn in @114 considered to be a correct output?

Again, please check if the output is a balanced tree.
