### ISSUE TITLE
[QZ4] Should the output tree a balanced tree?

### ISSUE THREAD

**Issue by ananthupucha** [emory-courses/dsa-java#114]
Do we need to have the tree completely balanced like and AVL tree? Or do we just need to make it where the left tree gets added to before the right?

For example, is this tree a correct output?

-

![image_50590209](https://user-images.githubusercontent.com/69823100/95819561-468aff00-0cf4-11eb-9212-ad7ad7205818.JPG)

**Comment by lujiaying** [comment]
I am waiting for Dr. Choi's response. But at this moment, please assume we want the output tree a balanced one.

**Comment by lujiaying** [comment]
Please take a look at : https://github.com/emory-courses/dsa-java/issues/117
