### ISSUE TITLE
[QZ#4] Input structure

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#115]
Are we assuming that the tree was balanced before the red key was added (i.e. the Uncle's child cannot have any children, else the height would differ by more than 1 so be unbalanced)?

**Comment by lujiaying** [comment]
I am waiting for Dr. Choi's response. I will reach back immediately once I know the answer.

**Comment by lujiaying** [comment]
From my understanding, the `BalacnedBinarySearchTreeQuiz` inherits `AbstractBalancedBinarySearchTree` class. So please assume that before `balance()`, the tree instance is already balanced.

**Comment by lujiaying** [comment]
Also, please take a look at https://github.com/emory-courses/dsa-java/issues/106
When conds not met, no need to conduct balance.
