### ISSUE TITLE
[QZ#4] Confused on the logic given.

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#116]
This question builds on the previous questions asked for this quiz.

So the expected output is a balanced tree. Say we get these trees as inputs:

![Tree Test](https://user-images.githubusercontent.com/59551654/95919481-a678b880-0d7b-11eb-8580-465cd82349a6.png)

This is what we were given as a logic map from Dr. Choi:

Override the balance() method that first checks the following conditions:
node is the only child &
node’s parent is the right child of node's grand parent &
node’s uncle has only one child.

Correct me if I'm wrong, but based off of the ruleset in the logic map given to us, the second input wouldn't execute any rotations. This would leave the tree unbalanced, wouldn't it?

**Comment by lujiaying** [comment]
Either of the three input trees are balanced. So I assume that I would not add such test cases.

**Comment by JonathanKimchi** [comment]
Okay, thank you. I will move forward with the understanding that the three trees listed are considered to be balanced for the criteria of this quiz.

**Comment by lujiaying** [comment]
Please take a look at : https://github.com/emory-courses/dsa-java/issues/117
