### ISSUE TITLE
[QZ4] 

### ISSUE THREAD

**Issue by mihirpatil001** [emory-courses/dsa-java#117]
Do we need to balance the height of the tree as it's done in AVL trees when doing the balance method implementation for this quiz? The quiz description in Exercises 4.4 doesn’t mention adjusting for the height of the tree as its done in AVL, but some of the answers to the GitHub issues are starting to confuse me as saying otherwise. One reply in #106 says we don’t need to do the balancing when the three conditions in the assignment description aren’t met, but then in #114 the reply says that we do need to make sure the output tree is a balanced tree as done with AVL. Can more clarification be provided on this, please?

**Comment by lujiaying** [comment]
Sorry for the confusion. I think I might say something wrong.

**Comment by lujiaying** [comment]
In case I mess up anything. I would not add my comments but just refer Dr. Choi's reply.

As it builds the tree, if the conditions are met, it will perform the balancing which may or may not end up generating a balanced tree

**Comment by mihirpatil001** [comment]
Ok, thank you for following up on this, I really appreciate it!
