### ISSUE TITLE
[QZ4] print tree

### ISSUE THREAD

**Issue by brendacano** [emory-courses/dsa-java#118]
When I try to print the tree using the toString function, it doesn't give me the numbers and instead gives me variations of BinaryNode@452459b3. How do I address this so I can check if my method actually works as well as to visualize AVLTree and RedBlackTree?

**Comment by JonathanKimchi** [comment]
What I did was print the value of the key using node.getKey();

**Comment by kristiey510** [comment]
I thinnk you can do something like this
<img width="640" alt="Screen Shot 2020-10-13 at 9 05 06 PM" src="https://user-images.githubusercontent.com/69918614/95931689-de8df480-0d97-11eb-9a7a-6306129805a5.png">

**Comment by brendacano** [comment]
> I thinnk you can do something like this
> <img alt="Screen Shot 2020-10-13 at 9 05 06 PM" width="640" src="https://user-images.githubusercontent.com/69918614/95931689-de8df480-0d97-11eb-9a7a-6306129805a5.png">

Thats what I did but it prints out as:
![2020-10-13 (1)](https://user-images.githubusercontent.com/69967655/95931937-725fc080-0d98-11eb-82b3-8c977d0dd898.png)

**Comment by kristiey510** [comment]
> > I thinnk you can do something like this
> > <img alt="Screen Shot 2020-10-13 at 9 05 06 PM" width="640" src="https://user-images.githubusercontent.com/69918614/95931689-de8df480-0d97-11eb-9a7a-6306129805a5.png">
> 
> Thats what I did but it prints out as:
> ![2020-10-13 (1)](https://user-images.githubusercontent.com/69967655/95931937-725fc080-0d98-11eb-82b3-8c977d0dd898.png)

hmm thats weird mine shows something like this
<img width="667" alt="Screen Shot 2020-10-13 at 9 12 03 PM" src="https://user-images.githubusercontent.com/69918614/95932043-bfdc2d80-0d98-11eb-8a6b-872647d14f33.png">

**Comment by JonathanKimchi** [comment]
^Yeah, you should use .getKey(). If you print the tree itself all you will get are the memory addresses of the pointers.

Kristi, did you write a .toString() method?

**Comment by kristiey510** [comment]
> ^Yeah, you should use .getKey(). If you print the tree itself all you will get are the memory addresses of the pointers.
> 
> Kristi, did you write a .toString() method?

no i just imported the classes that Dr. Choi had in his test
<img width="514" alt="Screen Shot 2020-10-13 at 9 13 15 PM" src="https://user-images.githubusercontent.com/69918614/95932136-0598f600-0d99-11eb-8d6a-15f9fc47b8b2.png">

**Comment by brendacano** [comment]
^ yeah i did the same thing, weird how it doesn't work for everyone

**Comment by JonathanKimchi** [comment]
Oh, that IS strange.

**Comment by brendacano** [comment]
Okay, I figured it out. In AbstractBinaryNode.java there is supposed to be this function:
    @Override
    public String toString() {
        return key + " -> (" + left_child + ", " + right_child + ")";
    }
I just looked through the codes and checked if there was a discrepancy between the code I had written code with the code in the repository. I added the function and now it actually prints.

**Comment by brendacano** [comment]
Thanks for the help guys, it helped me find the root of the issue.
