### ISSUE TITLE
[QZ0] src/main/java creating the package and build.gradle

### ISSUE THREAD

**Issue by brendacano** [emory-courses/dsa-java#12]
1. I don't know how to get to the src/main/java directory under the project so that I can create the package. I tried everything I could think of before I came here to submit this question for help. 

2. Also another issue I am having is that for build.gradle when I added the source and target compatibility it tells me that the assignment isn't being used. I wasn't sure if this was an issue and that I possibly did something wrong. I followed the previous instructions as accurately as I could. 

![2020-08-22](https://user-images.githubusercontent.com/69967655/90960283-9aa10200-e46e-11ea-82ca-ee06c6218b31.png)

**Comment by lujiaying** [comment]
Did you figure out the issue? 

If yes, we encourage you to share the solution you explored.

**Comment by brendacano** [comment]
The issue was fixed for the first part. IJ is a bit confusing but I found SRC under dsa-java and got both Utils and Utils.Test to work.

However, the build.gradle is still telling me the same two issues. I do not know why but I was hoping to ask during office hours.

**Comment by jdchoi77** [comment]
@brendacano for the record, you should not manually create the `src/main` directory since it is what gradle should automatically produce. If you do this manually, that implies that your gradle setting is not working correctly which will keep being an issue for your for the rest of the semester.

**Comment by brendacano** [comment]
@jdchoi77 I understand. I ended up finding it without making one, I think I had tunnel vision when I looking for it so hopefully, it worked out.
