### ISSUE TITLE
[QZ#5] Input Criteria

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#120]
If the word "United States" is on the list, should it trigger if it has a period at the end? For example "I was born in the United States."

**Comment by TFloyd1989** [comment]
Also, can we override the trie methods so that they return something that helps us differentiate non-list words?

**Comment by jdchoi77** [comment]
@TFloyd1989 you can override any part as needed if necessary.

**Comment by TFloyd1989** [comment]
> If the word "United States" is on the list, should it trigger if it has a period at the end? For example "I was born in the United States."

**Comment by lujiaying** [comment]
> If the word "United States" is on the list, should it trigger if it has a period at the end? For example "I was born in the United States."

Yes
