### ISSUE TITLE
Section 4.1

### ISSUE THREAD

**Issue by ddalama** [emory-courses/dsa-java#121]
Binary Search Trees: Section 4.1
-----

```
private void replaceChild(N oldNode, N newNode) {
    if (isRoot(oldNode))
        setRoot(newNode);
    else
        oldNode.getParent().replaceChild(oldNode, newNode);
}
```

In the above code (from AbstractBinarySearchTree class), L5 calls the superclass's method replaceChild(). Is this correct? If this is correct, how does the Java compiler know it has to call the superclass's replaceChild() method and not recursively call this class's replaceChild() method?

**Comment by marvinquiet** [comment]
It calls the oldNode's parent replaceChild function, which is in `AbstractBinaryNode` class.
