### ISSUE TITLE
[QZ5] input cases

### ISSUE THREAD

**Issue by zche377** [emory-courses/dsa-java#124]
Should we assume that each country name in the input String is a combination of independent words? Like, should we get "Canada" from "... aabbccCanada ..." ?

**Comment by zche377** [comment]
Also, is it case sensitive?

**Comment by lujiaying** [comment]
> Should we assume that each country name in the input String is a combination of independent words?

Trie is character-based. Introducing the idea of independent words is not necessary. 

> Also, is it case sensitive?

![image](https://user-images.githubusercontent.com/5207337/96326000-04ff9a00-0ffb-11eb-9a2f-247e41b85ccf.png)

Please take a look at this picture and see the character stored in every node.

**Comment by lujiaying** [comment]
Similar to the "America" - "American" case mentioned in Textbook,

>Like, should we get "Canada" from "... aabbccCanada ..." ?

The answer is yes.
