### ISSUE TITLE
[QZ#5] Robustness

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#126]
After working on the quiz for a few days, I've realized I have a few questions about what we should be prepared for.
1) Will country names in the list have punctuation? i.e("United States!", "South Korea!")
2) Will the String input have spaces? i.e Will it not look like this?(UnitedStatesSouthKorea)
3) Will you only test for country names?
4) What types of punctuation should we be prepared for within a sentence? i.e(&, ?, ., ,,) or any non word character?

**Comment by ananthupucha** [comment]
To add to this question, does the order of the final list of entities matter? Should the entities appear in the getEntities output list in the same order they appear in the input string?

**Comment by caroltang0331** [comment]
I dont think the order matters if you look at the code for "expected" and "actual" variable in the TrieQuizTest. but i could be wrong

**Comment by lujiaying** [comment]
The updated `notes` section https://emory.gitbook.io/dsa-java/tries/exercises#notes should answer all questions above.
