### ISSUE TITLE
[QZ#5] Embedded country names

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#127]
Replace `#` in the title with the appropriate quiz number.
Should we get "America" from the string "American"?

**Comment by marvinquiet** [comment]
I think you should not? Because America is the word in the tree but not American.

**Comment by Shreya3554** [comment]
in #124 the answer was to not consider the idea of independent words so that implies that "America" should be extracted from "American" right?

**Comment by marvinquiet** [comment]
We need to consult Dr. Choi and will get back to you later.
