### ISSUE TITLE
[HW#2] Commit dict.txt file

### ISSUE THREAD

**Issue by Abner3** [emory-courses/dsa-java#131]
Hello,
I get the following warning when I try to commit the dict.txt to GitHub.

![Screen Shot 2020-10-19 at 11 51 25 AM](https://user-images.githubusercontent.com/9061717/96498821-8f721480-121a-11eb-82da-e1006bc264b7.png)

I tried googling and I am still wondering whether to "Commit As Is" or "Fix and Commit".

**Comment by Abner3** [comment]
I went to the Office Hour and professor said Fix and Commit works just fine.

**Comment by lujiaying** [comment]
Sometimes we may not commit resource files into repository.
