### ISSUE TITLE
[QZ5] Output Entities Order

### ISSUE THREAD

**Issue by schun99** [emory-courses/dsa-java#132]
Should there be a certain order for output entities? I know in test case, it is United States and then South Korea. However, when I added more countries I get different orders. For example, when I added United States, South Korea, China, Chile as my list, then I get China, Chile, South Korea, and United States. Both begin/end index are correctly shown, but I'm just wondering if the order matters.

**Comment by lujiaying** [comment]
The Order does not matter.
