### ISSUE TITLE
[HW2] Question Regarding Test Methods 

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#134]
Hello! I am quite confused about the expected output of the test. In the unit test, the maximum number of candidates is set to be 20, but why do the expected outputs have only 3 strings instead of 20 strings? 

Also, technically, when the given prefix is "sh", shouldn't the first candidate be "sh" since it is the shortest word that starts with "sh" in the provided text file?

Thanks in advance.

**Comment by lujiaying** [comment]
> but why do the expected outputs have only 3 strings instead of 20 strings?

[L50](https://github.com/emory-courses/dsa-java/blob/master/src/test/java/edu/emory/cs/trie/autocomplete/AutocompleteTest.java#L50) examined 4 strings. So it is entirely possible we test arbitrary output strings.

> shouldn't the first candidate be "sh" since it is the shortest word that starts with "sh" in the provided text file?

I agree that "sh" itself can be a candidate. For this homework, I think it is just designed to be not including "sh" itself.

**Comment by lujiaying** [comment]
Hi @HallOfSam, just a clarification, your speculation is totally correct.

> From Dr. Choi's comment:
> 
> > those test cases as well as examples are dummies, not meant to be what's supposed to be implemented
> 
> That means if "sh" exists in dictonary.txt, please return it as well.

**Comment by HallOfSam** [comment]
> Hi @HallOfSam, just a clarification, your speculation is totally correct.
> 
> In #137,
> 
> > From Dr. Choi's comment:
> > > those test cases as well as examples are dummies, not meant to be what's supposed to be implemented
> > 
> > 
> > That means if "sh" exists in dictonary.txt, please return it as well.

Thank you!
