### ISSUE TITLE
[QZ5] Adjacent Entity Case

### ISSUE THREAD

**Issue by jbaek3** [emory-courses/dsa-java#136]
Should our code be able to handle two adjacent entities without a space in between? Such as "AlbaniaSouth Sudan". I couldn't figure out how to make this case work because end_index of Albania is exclusive and overlaps with the begin_index of South_Sudan. 

My code:
https://github.com/jbaek3/dsa-java/blob/master/dsa-java/src/main/java/edu/emory/cs/trie/TrieQuiz.java
Failed test with adjacent case: 
https://github.com/jbaek3/dsa-java/blob/master/dsa-java/src/test/java/edu/emory/cs/trie/TrieQuizTest.java

**Comment by lujiaying** [comment]
To me, in the case you mentioned you can ignore "South Sudan", but only extract the first entity "Albania".

**Comment by jbaek3** [comment]
Thank you, I figured it out. I had forgotten to assign the next potential word's beginIndex to the current index for when the child is a completed word as well as when it does not exist.
