### ISSUE TITLE
[HW2] Questions on speed and the return of getCandidates()

### ISSUE THREAD

**Issue by chloeslam** [emory-courses/dsa-java#137]
Question 1: To assess our algorithm speed, will our program speed be compared to our classmates? (similar to how it was assessed for HW1?)

Question 2: If getCandidates() has the input prefix of "sh" and "sh" exists in the trie, should getCandidates() return "sh" as a candidate?

**Comment by Abner3** [comment]
Answering Chloe's 2nd question, please read #134 .

Adding on to Chloe's 3rd question, would [ship, sheep, she] be a valid return for getCandidates?

**Comment by chloeslam** [comment]
@Abner3 Thank you for your referral! I think [ship, sheep, she] is a valid return because the most recent picked candidate was "ship", then the second most recently picked candidate was "sheep", and "she" the word that I chose to make the trie return first that was not recently picked

**Comment by Abner3** [comment]
@chloeslam I realized my question is incomplete and confusing since there are two versions of getCandidates we can implement (regular versus extra credit implementation). I edited out the question since the updated HW2 page clarifies my initial question.

**Comment by chloeslam** [comment]
@Abner3 Sounds good. Yeah, I was going to comment question 3 out because the HW2 clarifies it too. Thank you!

**Comment by lujiaying** [comment]
> If getCandidates() has the input prefix of "sh" and "sh" exists in the trie, should getCandidates() return "sh" as a candidate?

Yes.

**Comment by lujiaying** [comment]
> Question 1: To assess our algorithm speed, will our program speed be compared to our classmates? (similar to how it was assessed for HW1?)

I have not received the rubrics at this moment. But I guess it could be highly likely that way.

**Comment by chloeslam** [comment]
@lujiaying Thank you for your clarification! A question about your first answer though, I thought "sh" would not be returned since issue #134 was discussed that "sh" would not be returned?

**Comment by lujiaying** [comment]
> Thank you for your clarification! A question about your first answer though, I thought "sh" would not be returned since issue #134 was discussed that "sh" would not be returned?

In #134, "sh" not given in dictionary.txt, thus not exist in Trie tree.

In your case, you said "sh" is in Trie Tree. So following your assumption, the output is totally determined by the given dictionary.txt.

**Comment by chloeslam** [comment]
@lujiaying That makes sense. I appreciate your help so much, thank you!

**Comment by Abner3** [comment]
> > Thank you for your clarification! A question about your first answer though, I thought "sh" would not be returned since issue #134 was discussed that "sh" would not be returned?
> 
> In #134, "sh" not given in dictionary.txt, thus not exist in Trie tree.
> 
> In your case, you said "sh" is in Trie Tree. So following your assumption, the output is totally determined by the given dictionary.txt.

I am looking at dict.txt and it has "sh" in it.

**Comment by lujiaying** [comment]
> > > Thank you for your clarification! A question about your first answer though, I thought "sh" would not be returned since issue #134 was discussed that "sh" would not be returned?
> > 
> > 
> > In #134, "sh" not given in dictionary.txt, thus not exist in Trie tree.
> > In your case, you said "sh" is in Trie Tree. So following your assumption, the output is totally determined by the given dictionary.txt.
> 
> I am looking at dict.txt and it has "sh" in it.
> https://raw.githubusercontent.com/emory-courses/dsa-java/master/src/main/resources/dict.txt

Oh that is a good point. I need to ask Dr. Choi's opinion to see what is the expected output.

**Comment by lujiaying** [comment]
From Dr. Choi's comment:

> those test cases as well as examples are dummies, not meant to be what's supposed to be implemented

That means if "sh" exists in dictonary.txt, please return it as well.

**Comment by chloeslam** [comment]
@lujiaying Thank you!
