### ISSUE TITLE
[HW2] getCandidate and pickCandidate

### ISSUE THREAD

**Issue by Hodsonj** [emory-courses/dsa-java#139]
I have a question about how getCandidate and pickCandidate work together. Let's say I use:

candidates = getCandidate("sh")
pickCandidate("sh", "shack")

The pickCandidate should save shack but the variable candidates shouldn't change to have shack as the first element until I call:

candidates = getCandidate("sh") again. 

is this interpretation of how they operate correct?

**Comment by marvinquiet** [comment]
We need to consult Dr. Choi and come back to you later.
