### ISSUE TITLE
[QZ#0] Committing files to GitHub

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#14]
I followed the instructions from the exercises and the code works in my IDE, but it does not appear in my GitHub repository. My repository is missing the src folder, how do upload this to GitHub?

**Comment by lujiaying** [comment]
Did you figure out the issue? 

If yes, we encourage you to share the solution you explored.

**Comment by jdchoi77** [comment]
@lcunild this is most likely because you haven't pushed your changes to github.  Please make sure you commit and push the changes to github.
