### ISSUE TITLE
[QZ#5] Entity Overlap

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#140]
Is it okay if we define the same Entity twice(same exact indexes and ID)? My method does this sometimes in order to catch a particular case. When it outputs, that entity is only in the list once as well.

**Comment by marvinquiet** [comment]
I am not sure why would you need the same Entity twice? Could you please explain more about that?

**Comment by TFloyd1989** [comment]
It doesn't happen very often, but in order to get some edge cases, an entity may be defined twice in the process

**Comment by marvinquiet** [comment]
Got it! It should be fine as long as you can get the correct set of entities in the end.

**Comment by TFloyd1989** [comment]
Oh okay, thank you
