### ISSUE TITLE
[QZ#5] Clarification on the expect output.

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#141]
Hope everyone is doing well. I'll make this concise. We've been given these cases:

1. if "United States" is in the dictionary and "United Nations" is in the inputted string, then your algorithm should return no hits.
2. if "America" is in your dictionary and "American" is in the inputted string, then your algorithm should return a hit.

I wanted to ask about a third case. 

3. If "United N" is in your dictionary and "United Nations" is in the inputted string, should the algorithm return a hit?

I would love some clarification on this topic. As of right now, my algorithm is going to return an ArrayList of Entities that includes those generated by the case listed above.

**Comment by marvinquiet** [comment]
Yes, it is just a string matching. If there is a hit in the dictionary, you should return it.
