### ISSUE TITLE
[HW#2] sorted getCandidate()

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/dsa-java#143]
can we assume the words are alphabetically inserted in the trie because the dict.txt is alphabetically ordered? I just want to make sure of the edge case that the list of words read and put in the trie could be randomly ordered unlike a normal dictionary.

**Comment by marvinquiet** [comment]
Hi, sorry that I did not quite understand why would the order affect the result? Are you concerning when traversing the nodes one-by-one to find the next character, it will affect the time complexity?

**Comment by caroltang0331** [comment]
never mind it didn't affect my result. Sorry, I got it now.

**Comment by marvinquiet** [comment]
No worries! Glad to solve your problem!
