### ISSUE TITLE
[HW#2] introduce new words 

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/dsa-java#144]
if prefix didn't exist, should we add it? so next time when we call getCandidate(prefix), it will return both the picked candidate and itself as a candidate?

**Comment by caroltang0331** [comment]
actually I feel like it make more sense to not add it as a new word, and just leave it with EndState = false?

**Comment by caroltang0331** [comment]
actually i feel like we should, cuz u should put(prefix,cand) which makes prefix a word. Actually idk im confused

**Comment by caroltang0331** [comment]
im talking about the case when you pickCand() first then getCand(). I know if u never picked and the prefix dont exist, then just return null.

**Comment by caroltang0331** [comment]
Sorry if its confusing, basically I just want to know if the getCandidate() method should return the prefix itself in addition to the candidate that was picked ? like this prefix is not a real word in dict

**Comment by caroltang0331** [comment]
help lol

**Comment by marvinquiet** [comment]
If the prefix does not exist in the dictionary, then your candidates would be an empty list. You cannot pick candidates from an empty list, right?

**Comment by caroltang0331** [comment]
right okay thanks ! i guess im still confused about the end state. so, like we do pickCandidate("zzzzz", "hohoho") and then getCandidate("zzzzz"), should the returned result be {"hohoho"} or {"hohoho","zzzzz"} ?

**Comment by caroltang0331** [comment]
assuming "zzzzz" is never picked as a candidate, has no children, and did not exist before this

**Comment by caroltang0331** [comment]
i think it should just be "hohoho" right, we shouldn't include "zzzzz" because its a prefix its not a candidate?

**Comment by marvinquiet** [comment]
It depends on whether your prefix exists in the dictionary. If exists, then you need to add it to the candidate list
