### ISSUE TITLE
[HW2] Question Regarding List.contains()

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#145]
I am really confused about why List.contains() **always returns false** when I try to check whether a String is contained in the List. For example, I wrote the boolean statement: if (potentialCandidates.contains(allCandidates.get(i))) {...}. And this always returns false, including the scenario when potentialCandidates shares an identical element with allCandidates.

Moreover, when I try to compare two Strings (say s1 and s2) contained in List 1 and List 2, and the content of both of String is "she", s1.equals(s2) also returns false. This can't be right...

Can anyone explain this? Thanks in advance.

**Comment by HallOfSam** [comment]
Moreover, when I try to compare two Strings contained in List 1 and List 2, and the content of both of String is "she", equals() also returns false. This can't be right...

**Comment by chenda2000** [comment]
I'm not sure if you're using StringBuilder but I had an issue with contains() that turned out to just be StringBuilder adding a trailing whitespace to the end of every word in my list

**Comment by HallOfSam** [comment]
> I'm not sure if you're using StringBuilder but I had an issue with contains() that turned out to just be StringBuilder adding a trailing whitespace to the end of every word in my list

Thanx! I think I've figured it out.
