### ISSUE TITLE
[HW#2] pickCandidates question

### ISSUE THREAD

**Issue by chenda2000** [emory-courses/dsa-java#146]
I have two questions about pickCandidates(),

Should picking a candidate also affect its parent prefixes? For example:

If getCandidates("alpha") returns something like { ... , "alphabet", ... }
and we run pickCandidates("alpha", "alphabet"),
should something like getCandidates("alph") give you {"alphabet", ... , ... }? Or would only the candidates of "alpha" change?

Can we assume that any picked candidate is one of the candidates from getCandidates? For example:

If the candidates of "a" are {"a", "aa", "ab"}, would pickCandidates("a", "adding") do nothing or would the candidates of "a" become {"adding", "a", "aa"}?

**Comment by lujiaying** [comment]
> should something like getCandidates("alph") give you {"alphabet", ... , ... }? Or would only the candidates of "alpha" change?

From my understanding and the function definition, 
the `pickCandidate()` method that takes a prefix and a selected candidate, and saves the information:
- This is the most recently selected candidate for that **particular prefix**

**Comment by lujiaying** [comment]
> If the candidates of "a" are {"a", "aa", "ab"}, would pickCandidates("a", "adding") do nothing or would the candidates of "a" become {"adding", "a", "aa"}?

This question is tricky. I am not sure, so please maybe waiting for Dr. Choi's opinion. (*In my mind, it should include "adding" into the candidate list*)

**Comment by chenda2000** [comment]
Thanks for the answers!

>This question is tricky. I am not sure, so please maybe waiting for Dr. Choi's opinion. (In my mind, it should include "adding" into the candidate list)  

Dr. Choi said during lecture that we should include it even if it's not in the list (and even if it doesn't start with the prefix, like pickCandidates("a", "boy") gives {"boy", "a", "aa"})
