### ISSUE TITLE
[QZ#0] connection refused to GitHub

### ISSUE THREAD

**Issue by alexbingqi** [emory-courses/dsa-java#15]
Replace `#` in the title with the appropriate quiz number.
As I sharing the project on the GitHub, the IDE shows that cannot run Git. I am using a mac.
![image](https://user-images.githubusercontent.com/69951650/91021571-8acc1e00-e626-11ea-9f22-e2e932bb424b.png)

**Comment by lujiaying** [comment]
Could you check #13 to see if your situation is similar?

**Comment by alexbingqi** [comment]
a new error with this warning pops up.
![image](https://user-images.githubusercontent.com/69951650/91060264-4d36b780-e65d-11ea-8fd4-fb425630d003.png)

**Comment by jdchoi77** [comment]
@alexbingqi I l believe this is the same issue as #3 and the instruction has been also updated to the book chapter so please take a look.

**Comment by alexbingqi** [comment]
I have a push that failed. 
![image](https://user-images.githubusercontent.com/69951650/91065065-a05f3900-e662-11ea-81da-258022a740f3.png)

**Comment by jdchoi77** [comment]
@alexbingqi this means your github account is not setup properly in IntelliJ.

**Comment by alexbingqi** [comment]
I have followed the textbook to add my Github account and it has been successful. What should I do to enable the permission?

**Comment by lujiaying** [comment]
> I have followed the textbook to add my Github account and it has been successful. What should I do to enable the permission?

Did you figure out the permission issue?

If not, to be honest, I kind of lose the context for the `permission`. What does it stand for?

**Comment by alexbingqi** [comment]
By attending the office hour, I found out that I missed an SSH public key and I have already figured out.
