### ISSUE TITLE
[QZ#6] Question on Graph input

### ISSUE THREAD

**Issue by Schm2000** [emory-courses/dsa-java#150]
For the GraphQuiz method numberOfCycles(), should we expect for the graph input to possibly have multiple edges between two specific vertices or should we expect for the graph to only have one edge between two specific vertices?

**Comment by lujiaying** [comment]
From what I learned back to my bachelor time, in the learning stage we typically not consider multi-view graph (multiple edges between two vertices). But I still recommend to ask Dr. Choi for his opinion.

**Comment by Schm2000** [comment]
Alright, I will ask him.
