### ISSUE TITLE
[HW#2] Whitespace Handle

### ISSUE THREAD

**Issue by LukHan99** [emory-courses/dsa-java#151]
In the note's of the homework, Dr. Choi wrote that "Whitespaces are not allowed as input; thus, you should trim all input strings." so I just want to make sure that does this sentence mean: inputs consist of only spaces like "      " are not allowed as input, but the empty string "" and inputs with a combination of characters and spaces like "ap p l e " are allowed. For inputs like "ap p l e ", we should trim it and consider "apple" as the prefix. 

Also, if my above logic is true, does it mean that we need to write exception catch blocks to catch inputs which consists of only spaces like "      ", or we should just ignore this case since it will not be tested? Thanks!

**Comment by lujiaying** [comment]
The edge case is good. I am glad to see you are trying to make the code robust.

I think for this homework, it is not necessary to consider such a complex case. "ap p l e" typically will be recognized as multiple word "ap", "p", "l", "e'. 
For `trim`, it  eliminates leading and trailing spaces, but not the middle spaces.

**Comment by jdchoi77** [comment]
@LukHan99 by trimming means that you need to remove whitespaces before and after the real word, not in between.
