### ISSUE TITLE
[QZ6] Arrow in tree direction

### ISSUE THREAD

**Issue by Hodsonj** [emory-courses/dsa-java#154]
Does the arrow direction mean anything? I've researched other disjoint-set tree visualizations and a lot of them have the arrows going the other way to the "root"?

**Comment by lujiaying** [comment]
In my mind, the tree maybe is just a dummy example since in disjoint sets, there is no direction between elements.

**Comment by jdchoi77** [comment]
From a theoretical point of view, the arrows don't mean anything but they mean something for this quiz because it represents which becomes the parent and the child.
