### ISSUE TITLE
[HW#2] Test output

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#156]
When I use the test program, my program returns exactly the same output as the expected output, however it still says fail.
![Screen Shot 2020-10-29 at 1 17 34 PM](https://user-images.githubusercontent.com/70056741/97578733-1ed0b200-19e9-11eb-95fd-67569fe56cf9.png)
What could be causing this to happen?

**Comment by lujiaying** [comment]
That could be due to the check condition statement.
In java, if want to check two arrays equality, `assertArrayEquals` or other alternatives are recommended.

Simply use `assertEquals(arrA, arrB)` might lead to the above situation because it examined the memory address of `arrA`, `arrB`.

**Comment by lcunild** [comment]
Here is my getCandidates method for Autocomplete: [https://github.com/lcunild/dsa-java/blob/master/src/main/java/edu/emory/cs/trie/autocomplete/AutocompleteHW.java](url)
It is not finished yet, I am just trying to get it to work for the basic case, and then make it more robust once I know that my idea is correct.
Here is the test program: [https://github.com/lcunild/dsa-java/blob/master/src/test/java/edu/emory/cs/trie/autocomplete/AutocompleteTest.java](url)

**Comment by lcunild** [comment]
I figured out the reason why, I had added a null character to the end of all my strings in the result. I have fixed it now.
