### ISSUE TITLE
[HW#2] NullPointer Exception

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#157]
I keep getting a null pointer exception whenever I try to add to the string list of any given node. How do I add to it so that it stops giving a null pointer exception?

**Comment by marvinquiet** [comment]
Did you find out what caused this exception? I assume you visited some null character nodes.

**Comment by TFloyd1989** [comment]
Yes, I was able to figure it out

**Comment by marvinquiet** [comment]
Then, just avoid accessing the null node would help
