### ISSUE TITLE
[HW2] Getting Children

### ISSUE THREAD

**Issue by DHuryn** [emory-courses/dsa-java#158]
Is it ok if we use the "getChildrenMap" method for efficiency? Dr. Choi said we can use the built in methods even though they have maps, but I wanted to confirm we can use this. I am getting the map and immediately converting it to a 2d array without using any map properties beforehand.

**Comment by DHuryn** [comment]
To clarify, the getChildrenMap(l method from into the Trie class written by Dr. Choi

**Comment by jdchoi77** [comment]
@DHuryn yes you can use anything that's built into Trie including the children map. You are just not allowed to create any new map.
