### ISSUE TITLE
[QZ6] Confusion on the tree graph of disjoint set

### ISSUE THREAD

**Issue by BaichenRong** [emory-courses/dsa-java#159]
I might be stupid but I really don't understand what it means in this graph. 
![image](https://user-images.githubusercontent.com/69851166/97672784-02705c00-1a61-11eb-84aa-5ac808a55020.png)
Does that mean [3,1,0],[3,2] and[3,4] are 3 separated unions?
Are we going to set up such a union by using find method only?

**Comment by jdchoi77** [comment]
@BaichenRong according to the figure above, all keys end up being in the same set although how each key gets merged is different.
