### ISSUE TITLE
[QZ0] Methods in Utils and UtilsTest

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#16]
Should the code in these files be the code given in the textbook or the code from the links on Quiz 0? There are extra methods in the code on Canvas that are not included in the textbook exercises.

**Comment by lujiaying** [comment]
Could you provide more information about "extra methods" on Canvas?

**Comment by lcunild** [comment]
In the links under 'Submissions' on canvas the file for Utils has the following methods which are not included in the textbook:

static public int[] getRandomIntArray(Random rand, int size) {
        int[] array = new int[size];

        for (int i = 0; i < size; i++)
            array[i] = rand.nextInt();

        return array;
    }

    static public double log2(int i) {
        return Math.log(i) / Math.log(2);
    }

    static public void main(String[] args) {
        System.out.println(getMiddleIndex(0, 10));
    }

The UtilsTest file on canvas has one extra method not in the textbook:
 `@Test
    public void testst() {
        System.out.println("SDFSFs");
    }`

**Comment by jdchoi77** [comment]
@lcunild for quiz 0, no need to include those extra methods, which we will be using throughout the semester.
