### ISSUE TITLE
[HW2] Non-exiting Prefix and methods for Putting words into Trie

### ISSUE THREAD

**Issue by ywu496** [emory-courses/dsa-java#160]
Fisrt question: 
For the getCandidate() as well as pickCandidate() method, if a prefix that doesn't exist in the Trie gets used as a parameter, should I make the prefix into a word(endState = true), or just add the prefix to the Trie structure without acknowledging it as a legitimate word(endState = false). Moreover, when getCandidate() gets called using a non-exisiting prefix, should I return nothing, or return just the prefix(assume it is the first time the non-exisitng prefix is being called)?

Second question: 
When the HW is being graded, how are the words put into the Trie in the process? Is it by using the "put" method in the parent class? If it is, is the TrieNode variable "value" initialized to null when putting words into the Trie?

**Comment by jdchoi77** [comment]
1a. prefix should be introduced to the trie but not as a word when it is passed to the pickCandidate() method.
1b. the first time when getCandidate() is called on non-existing prefix, it should return an empty list.
2. all values will be null initially.
