### ISSUE TITLE
[HW#2] Adding non-existing candidates?

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#164]
Replace `#` in the title with the appropriate homework number.
For pickCandidate(prefix, candidate), if the candidate does not exist, do we need to add the candidate to the trie?

**Comment by TFloyd1989** [comment]
Adding to this question, should the word be labeled as a dictionary term via its endstate as well?

**Comment by skhardi** [comment]
To my understanding, yes if the candidate is not already in the trie, it should be added with its endstate set to true. If the prefix is not in the trie, then it should be added to trie but the endstate will be false.

**Comment by marvinquiet** [comment]
Thank you @skhardi for answering!
