### ISSUE TITLE
[QZ6] Clarification for cycle counting 

### ISSUE THREAD

**Issue by ywu496** [emory-courses/dsa-java#166]
For the graph below, is it considered two cycles(1<-- 2 <-- 3 <-- 4 <--1 and 1 <-- 5 <-- 4 <-- 1)
If it is considered two circles, is it possible to visit all nested circles without traversing any node more than once(I had to traverse the node 4 twice using incoming edges for traversing)? 
![d63fd79da044341a99726e1aa4cfabe](https://user-images.githubusercontent.com/69917863/97789289-a22f0680-1b95-11eb-8bd0-f195d77f45f6.jpg)

**Comment by marvinquiet** [comment]
Yes, in this case, you will be visiting node 4 twice because there is a shared edge between two cycles.

**Comment by jdchoi77** [comment]
@ywu496 you don't necessarily the node 4 twice, instead you make two separate recursive calls from the node 4 while making 1 visit.
