### ISSUE TITLE
[QZ#6] Baseline vs Efficient

### ISSUE THREAD

**Issue by alexbingqi** [emory-courses/dsa-java#168]
There is no difference in the result whether we use baseline find method or efficient find method due to the method Union. Both of the find methods will give out the root of the sets. However, the union method let subsets[r2] = r1 or subsets[r1] = r2 will directly make the subset all points to the root instead of to the set's parent. After I turn  subsets[r2] = key1 or subsets[r1] = key2, the subset will be different for baseline and efficient. 

Therefore, should we need to include that in our report? As I believe, the baseline should have a different result with the efficient method. However, if we do not change the union method, both of the find methods will give the same answer.

**Comment by BaichenRong** [comment]
I also found out the same issue when printing out the result

**Comment by marvinquiet** [comment]
Yes, you can summarize your findings in your report.
