### ISSUE TITLE
[QZ#6] Having previously visited nodes as part of cycle?

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#170]
Replace `#` in the title with the appropriate quiz number.
For the quiz, are we assuming that each cycle path contains no repeating nodes? For example, in the scenario below, would 1->2->3->4->3->2->1 be considered a cycle? If so, the solution would be very complicated. 
<img width="346" alt="Screen Shot 2020-11-01 at 10 17 54 AM" src="https://user-images.githubusercontent.com/69922387/97810958-609d6a80-1c2c-11eb-844f-7e41676e47ee.png">

**Comment by marvinquiet** [comment]
According to the requirement of the homework, you need to `Make sure to handle nested cycles.` But you may want to consult Dr. Choi in class to make sure about this edge case.
