### ISSUE TITLE
[HW2] Extended Deadline 11/11 ?

### ISSUE THREAD

**Issue by HowardYutingHou** [emory-courses/dsa-java#171]
As the official deadline for homework 2 is 11/4, will the extended deadline with penalty be 11/11, which is a week after?

**Comment by marvinquiet** [comment]
Please directly consult Dr. Choi about this. But according to the syllabus, `Late submissions within a week will be accepted with the grading penalty of 15%, and will not be accepted after the first week. Exceptions to this policy will be made only in extraordinary circumstances.`
