### ISSUE TITLE
[QZ#6] Graph Edge Weight

### ISSUE THREAD

**Issue by LukHan99** [emory-courses/dsa-java#173]
Can we assume that the weights of the edges in the graph will all be set to 0 when the graph is constructed?

**Comment by LukHan99** [comment]
If it is not a reasonable assumption, then are we allowed to change the weights of the edges in the graph?

**Comment by marvinquiet** [comment]
For detecting cycles, we can just consider it as 0 because we focus more on the direction of edges.
