### ISSUE TITLE
[QZ#6] Adjacent Cycles

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#174]
![Screenshot (52)](https://user-images.githubusercontent.com/69921592/98426341-7369d200-2066-11eb-91f4-687b3b3cfe5e.png)
For the graph in test case #6 in 7.4, I seem to be triggering a cycle for the combination of two other cycles, [2 4 5] and [0 3 4]. I was wondering about any logical ways to help solve this case?

**Comment by TFloyd1989** [comment]
I've thought of this problem more, and I now have a more specific question regarding cycles. Generally, how do you stop a verticie from being used in cycle detection twice?

**Comment by marvinquiet** [comment]
By using the "notVisited" list.
