### ISSUE TITLE
Misc) Intellij errors.

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#175]
I am getting the error: Execution failed for task ':test'.
> Unexpected result file version 0 found in C:\Users\worke\IdeaProjects\dsa-javaTFII\build\test-results\test\binary\results.bin.

whenever I try to test my HW 2 code. I have also included a screenshot, I was wondering how I get around this error.
![Screenshot (55)](https://user-images.githubusercontent.com/69921592/98590295-97aef400-229c-11eb-8e25-358783618435.png)

**Comment by TFloyd1989** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/69921592/98592568-e6aa5880-229f-11eb-88ae-dbf4fd9e1304.png)
More information with stacktrace

**Comment by lujiaying** [comment]
Never seen this before. Could you try `compile` to see if there are typos somewhere in the code?

**Comment by huynhduchuydp36** [comment]
Delete file results.bin as in report, it work for me.

**Comment by Duduxs** [comment]
Deleting the file works for me too!
