### ISSUE TITLE
[HW#2] Late Resubmission

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#176]
I see that there's no submit button on canvas for HW2. If we are submitting late, all we do is push our code to our repository for the Hw and extra credit?

**Comment by marvinquiet** [comment]
Hi, I think the submission may be closed several days after the due date. I can ask Dr. Choi about it.

**Comment by TFloyd1989** [comment]
Okay, thank you. In the meantime I've pushed my code

**Comment by jdchoi77** [comment]
@TFloyd1989 nothing to be submitted on canvas, just push your code to github.
