### ISSUE TITLE
[QZ7]  isolated vertices

### ISSUE THREAD

**Issue by zche377** [emory-courses/dsa-java#177]
In minimum spanning tree, can we assume that there's no vertex with zero edge, since by definition "a spanning tree in a graph is a tree that contains all vertices in the graphs as its nodes"?

**Comment by marvinquiet** [comment]
Very good question. I think we need to assume all vertices are at lease somehow connected, otherwise, the MST concept does not work.

**Comment by zche377** [comment]
thank you!
