### ISSUE TITLE
[HW#3] MSTWordHW Question

### ISSUE THREAD

**Issue by Kaseyc27** [emory-courses/dsa-java#178]
I was wondering where we have to implement MSTWordHW for HW#3? It is not mentioned anywhere on the page. There is //todo comments on it, so i'm guessing that this is utilized for a MST tree with characters(A-Z) instead of numbers?

**Comment by marvinquiet** [comment]
According to what I read from the page, `Create a class called MSTAllHW that inherits the MSTAll interface.`. I am not sure if it is already an updated one.
