### ISSUE TITLE
[QZ#8] weight of edges 

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/dsa-java#179]
For the augmented path, do we assume the weight of all edges are greater than 0? if it's 0, should we still consider that a valid edge to be part of the path.

**Comment by lujiaying** [comment]
For edge weights, do you mean edge capacity in the original graph?

**Comment by caroltang0331** [comment]
> For edge weights, do you mean edge capacity in the original graph?

yes thats wut i meant, sorry

**Comment by lujiaying** [comment]
I think for the general flow network, the capacity is non-negative.

**Comment by caroltang0331** [comment]
okay thank you!
