### ISSUE TITLE
[QZ#6] DisjointSet Grading Question

### ISSUE THREAD

**Issue by chenda2000** [emory-courses/dsa-java#182]
I got a point off of my DisjointSetQuiz implementation:

-1 Correctness: Expected: [1, 3, 3, -5, 3], Got: [3, 3, 3, -5, 3]

But when I run my code, I get the correct tree [1, 3, 3, -5, 3] using the baseline find() method. Using the efficient find() gives [3, 3, 3, -5, 3].

According to the assignment page, we were supposed to assume that we were using the baseline version of find() for the implementation, so I was wondering if this was a mistake?

**Comment by lujiaying** [comment]
Oh you are correct. I used the efficient version to examine your implementation. The grade would be recover.

**Comment by lujiaying** [comment]
Sorry for the mistake.
