### ISSUE TITLE
Announcement Clarification

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#185]
I was just wondering if I concatenate the null character in my code. If the prefix is empty, I make the prefix equal to an empty space "" which I then get the children of. I'm pretty sure this is the root node. For the first iteration of my BFS, I do prefix + key in a loop, which I think concatenates the root character. I have also included a screenshot.![image](https://user-images.githubusercontent.com/69921592/99818643-78298e00-2b1c-11eb-8307-1f90fdad4584.png)

**Comment by marvinquiet** [comment]
The new announcement if for those who accidentally concatenate the string up to the root (which is null) and return as a list. In this way, only by asserting can they find the error, and simply printing won't help. 

In your case, it seems that the logic is correct, but

(1) It seems that you did not trim the word with there is a whitespace
(2) what will you get when you simply use "she" as your prefix? From my end, there are exceptions in your output.

**Comment by TFloyd1989** [comment]
I trim the word earlier in my code in line 35 if the string is not blank, and I used the prefix she while testing which never gave me any errors.

**Comment by TFloyd1989** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/69921592/99822339-13bcfd80-2b21-11eb-9342-0e04178333ed.png)
This is the output for she with no changes to my code

**Comment by marvinquiet** [comment]
May I know what does that 's}' represent? Also, could you drag it a bit more or paste it here so that I can see the whole return list?

**Comment by marvinquiet** [comment]
Oh, I see, the 's}' is your candidate, could you please share all the output then?

**Comment by TFloyd1989** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/69921592/99822718-904fdc00-2b21-11eb-84e1-fadc54ddb16e.png)
![Screenshot (65)](https://user-images.githubusercontent.com/69921592/99822734-92b23600-2b21-11eb-99e4-c2a123e9969f.png)
Here are all of the tests and results

**Comment by TFloyd1989** [comment]
(All testing done with original code)

**Comment by marvinquiet** [comment]
Could you please try changing your candidate to null and see what happened?

**Comment by TFloyd1989** [comment]
I get a null pointer exception

**Comment by marvinquiet** [comment]
When testing your code with null as candidate, this is what I get

![image](https://user-images.githubusercontent.com/7233574/99823036-e3299380-2b21-11eb-9954-062f3bf9d191.png)

So according to textbook you did not deal with followings:

```
Your program should be able to handle prefixes or candidates that do not exist in the dictionary.
All picked candidates should be introduced as real words to the trie.
Whitespaces are not allowed as input; thus, you should trim all input strings.
```

**Comment by TFloyd1989** [comment]
Is this for when the candidate is null?

**Comment by marvinquiet** [comment]
Yes, you may want to fix that error within two lines of code change before 1pm

**Comment by TFloyd1989** [comment]
For the value null, should we enter "null" into the list as a string or nothing at all?

**Comment by marvinquiet** [comment]
You don't need to insert null into this. For a null candidate, you just return the candidates for the prefix as usual and it should be solved with 1 line. 

Yes, in total, 2 lines at most

**Comment by TFloyd1989** [comment]
For example, if a given candidate sh has the candidates shell and sheep, getcandidates should return shell and sheep if pickcandidates contains null?
