### ISSUE TITLE
[QZ#8] Augmenting paths question

### ISSUE THREAD

**Issue by chenda2000** [emory-courses/dsa-java#186]
![ford-fulkerson-algorithm-1-1024](https://user-images.githubusercontent.com/69917888/99917241-f6349300-2cdc-11eb-9ef7-2e2822184d00.jpg)

For this graph, are [S, 1, 3, 2, 3, T] or [S, 2, 3, 2, 4, T] considered augmenting paths? They repeat vertices, but don't repeat edges so I wasn't sure

**Comment by marvinquiet** [comment]
Hi, 

The graph can have cycles but the augmented path should not have cycles.
