### ISSUE TITLE
[QZ#8] Path Clarification

### ISSUE THREAD

**Issue by LukHan99** [emory-courses/dsa-java#187]
When we are returning the augmented paths, are we required to start the subgraph from the source index? For instance, if we have found a path: 3->4->5 where 3 is the source and 5 is the target, do we need to return the path as: [4 <- 3, 5 <- 4] or [5 <- 4, 4 <- 3], or either way is fine?

**Comment by marvinquiet** [comment]
Hi,

Please check it here:
https://github.com/emory-courses/dsa-java/blob/e704f481c0da7c4fe180ebb3a2d5488db8fcf5bc/src/main/java/edu/emory/cs/graph/flow/FordFulkerson.java#L102
