### ISSUE TITLE
[QZ0] Can't import from org.junit 

### ISSUE THREAD

**Issue by ywu496** [emory-courses/dsa-java#19]
When I tried to do the test for UtilsTest.java, errors appeared saying "package org.junit does not exist". I wonder if I need to install the package beforehand, or if the problem lies somewhere else. 
![buhuo2](https://user-images.githubusercontent.com/69917863/91095810-ef897780-e62a-11ea-8c6a-44eae5bacc1e.JPG)

**Comment by lujiaying** [comment]
`UtilsTest.java` should be placed under `src/test/java`. 
From your screenshot, it seems that unit test file is accidentally under `src/main/java`.

**Comment by ywu496** [comment]
Oh, thanks so much.
