### ISSUE TITLE
[HW#3] only one vertex case

### ISSUE THREAD

**Issue by chenda2000** [emory-courses/dsa-java#191]
For graphs of only one vertex, should we return an empty list or a list with one empty SpanningTree?

Basically, is a spanning tree with no edges still considered a spanning tree?

Edit: I also have the same question for graphs of zero vertices

**Comment by marvinquiet** [comment]
There will be multiple nodes with edges connecting them.

**Comment by chenda2000** [comment]
Are you sure? There are several cases in the test file with no edges (complete graph of size 1, getGraph1a, and getGraph2a)

**Comment by marvinquiet** [comment]
Yeah, according to what Dr. Choi replied to me earlier. But feel free to go to today's office hours and check with Dr. Choi directly

**Comment by chenda2000** [comment]
Dr. Choi said if a graph has no edges we should return an empty list

**Comment by marvinquiet** [comment]
Thanks! Good to know
