### ISSUE TITLE
[HW3] Expected Run time

### ISSUE THREAD

**Issue by ananthupucha** [emory-courses/dsa-java#192]
How large will the graphs in the test cases get and how fast is our algorithm expected to be? I made a relatively large graph with 10 vertices and 13 edges that contained 45 MSTs, but it took around 50 seconds to find all of them. Is this too slow and will points be taken off if our algorithms take too long?

**Comment by marvinquiet** [comment]
When the graph gets large, it will become slow according to your implementation. But in my opinion, it should not be this slow for 10 vertices and 13 edges.
