### ISSUE TITLE
[HW#3] Kruskal Modification Specifics

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#196]
By using a modified Kruskal's algorithm, I am close to returning all MSTs. However, I am unsure how I explore all of the potential MSTs that share the same edge weight because Kruskal can make an MST that features more than one edge with the same weight. How should we explore all MST paths given that multiple edges at the same weight could be selected?

**Comment by lujiaying** [comment]
That's a good question. I think to conduct an exhaustive search is the critical part for this hw. 

From an abstract level perspective,  either keeping a record of same weights edges or continuing search until all edges are visited may be helpful.
