### ISSUE TITLE
[HW#3]  how to submit extra source code?

### ISSUE THREAD

**Issue by HowardYutingHou** [emory-courses/dsa-java#198]
hello, how do we submit the source code for the extra credit? Push to github? Or, do we submit java file to canvas? 

if we submit java file to canvas, do we remove the package headings?

**Comment by lujiaying** [comment]
Could you create a java file, say `MSTAllHWTestExtra.java` and push it to GitHub?  Like the way we did in [HW2](https://emory.gitbook.io/dsa-java/tries/homework).
