### ISSUE TITLE
[QZ1] Gradle Version?

### ISSUE THREAD

**Issue by bianshuyang** [emory-courses/dsa-java#202]
I let the IntelliJ automatically decides the gradle to download and therefore it shows: distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
Is it a problem? Since the textbook says:
Open gradle/wrapper/gradle-wrapper.properties and make sure distributionUrl indicates the latest version of Gradle:
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
If it indeed is a problem, I don't know how to fix it.

**Comment by TobiE0808** [comment]
I also have a similar question. I am trying to follow the steps for Quiz 0, and I am currently stuck at the part about preferences-build section. I can't find the menu and I am not sure if it is on IntelliJ or on github.

**Comment by ynd24** [comment]
> 

I have the same issue, I cant find the menu in order to click [Preferences - Build, Execution, Deployment] and set Gradle JVM to 17.
