### ISSUE TITLE
[QZ#1] Overriding addDifferentSigns

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#21]
I successfully made addDifferentSigns successfully work while within the longinteger file, however when I copy and pasted the method contents into Longintegerquiz and labeled it override and replaced the original addDifferentsigns, the add method will only call the version of addDifferentSigns that throws an error. Also I get an error when I try to run longintegerquiztest because there are 1 arguments in longintegerquiz when there should be 0.``

**Comment by lujiaying** [comment]
Could you provide the code snippet to make the question more clear?
I can hardly reproduce the error with limited information provided.

**Comment by TFloyd1989** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/69921592/91605895-3636e480-e93f-11ea-98aa-694e570709cb.png)
![Screenshot (5)](https://user-images.githubusercontent.com/69921592/91605909-3b942f00-e93f-11ea-86df-f08b57e1e367.png)
![Screenshot (4)](https://user-images.githubusercontent.com/69921592/91605920-3f27b600-e93f-11ea-95ba-8b9c72fdcf5b.png)
![Screenshot (2)](https://user-images.githubusercontent.com/69921592/91605932-4222a680-e93f-11ea-8287-dcc8308ccd0f.png)

**Comment by TFloyd1989** [comment]
Included are both versions of the addDifferentsign, as well as the error message when I try to run add. I have also included a screenshot of the longintegerquiztest errors.

**Comment by lujiaying** [comment]
@TFloyd1989 thanks for the screenshots.

From the first screenshot, error in L28 could be due to:

```Java
LongInteger a = new LongInteger("123");  //change LongIntegerQuiz to LongInteger
``` 

Please pay more attention to these kinds of errors caused by typos. And try to fix all similar typos.

**Comment by TFloyd1989** [comment]
Thank you, however, that was the state of the file after I downloaded it from the textbook. Specifically, it said LongIntegerQuiz rather than longinteger.
![Screenshot (7)](https://user-images.githubusercontent.com/69921592/91607013-346e2080-e941-11ea-8da1-e32566c07450.png)

**Comment by lujiaying** [comment]
@TFloyd1989 Sorry. I have not go through the quiz1. So my previous response was indeed wrong. Please give me some time to figure out myself and then reach back to you.

Thanks.

**Comment by TFloyd1989** [comment]
Oh okay, no problem and thank you for the help!

**Comment by lujiaying** [comment]
From the first screenshot, error in L28 could be due to:

The constructor function that specifically has one input `String` argument is not implemented for `LongIntegerQuiz`.

We can **mimic** (not copy; also please try the `super()` trick) the constructor function in `LongInteger.java` to implement our own constructor function.

```Java
   /**
     * Creates a long integer by copying the specific object.
     * @param n the object to be copied.
     */
    public LongInteger(LongInteger n) {
        super(n.sign);
        digits = Arrays.copyOf(n.digits, n.digits.length);
    }

    /**
     * Creates a long integer with the specific sign and values.
     * @param n the sign and values to be set.
     * @see #set(String)
     */
    public LongInteger(String n) {
        set(n);
    }
```

**Comment by lujiaying** [comment]
@TFloyd1989 does it solve the issue?

**Comment by TFloyd1989** [comment]
I wasn't too sure how to implement it, I'm planning on coming to office hours today at 2:30 to discuss it in more detail as well

**Comment by TFloyd1989** [comment]
My code appears to match the one above word for word now that I'm looking at it

**Comment by jdchoi77** [comment]
@TFloyd1989 as we talked about this over the office hour, please let me know if it becomes the issue after you create constructors for `LongIntegerQuiz`.  Thanks.
