### ISSUE TITLE
[QZ0] 1) Gradle/wrapper...  2) adding files/committing  3) src/main/java

### ISSUE THREAD

**Issue by ghost** [emory-courses/dsa-java#22]
Hello, 

I have the following issues and would appreciate guidance on how to solve them:

1) I cannot see gradle/wrapper/gradle-wrapper.properties and therefore I cannot open it. 

2) The end of Textbook chapter 0.1 states, "Add all files and make the initial commit.  Check if the repository is created under your GitHub account." I am unsure about how to add all files and make the initial commit. Please suggest how I should do this. Also, how many files should we see in the repository in our GitHub account?

3) I cannot view src and so cannot access src/main/java. 
********************************************************************************************
I have attached a screenshot of my IntelliJ IDEA window below:

<img width="1440" alt="HW0 IDEA" src="https://user-images.githubusercontent.com/70102750/91645932-8c06ac00-ea67-11ea-9054-3de544bd2895.png">

**Comment by lujiaying** [comment]
For 1 and 2, please refer to https://github.com/emory-courses/dsa-java/issues/12

It may take several minutes for IntelliJ to download all needed files and create directories.

After `gradle/wrapper/gradle-wrapper.properties` and other directories are created, then we can follow the tutorial to proceed.

**Comment by lujiaying** [comment]
@ddalama There are several ways to force Gradle update all dependencies:

> On the Gradle tab (right side of UI), click the blue circling arrows icon, which should refresh the dependencies (works in most cases)
> If that does not work, try running the Gradle command in IntelliJ using the Green "run Gradle command" icon - this runs the command in IntelliJs environment not that of your local machine.

From [stackoverflow](https://stackoverflow.com/questions/32652738/how-can-i-force-update-all-the-snapshot-gradle-dependencies-in-intellij)
