### ISSUE TITLE
[QZ#1] JAVA problem during running the class

### ISSUE THREAD

**Issue by alexbingqi** [emory-courses/dsa-java#23]
I don't know what happens.

![image](https://user-images.githubusercontent.com/69951650/91693865-426cad00-eb9e-11ea-8899-7ee6a29d5185.png)

**Comment by lujiaying** [comment]
Could you use "debug" instead of "run" to see the detailed logs?

**Comment by alexbingqi** [comment]
![image](https://user-images.githubusercontent.com/69951650/91717731-a30ee080-ebc4-11ea-8874-06ec3c9980a9.png)
This is what I get after the debug.

**Comment by marvinquiet** [comment]
May I see your configuration file especially what is your input as arguments?

**Comment by lujiaying** [comment]
> ![image](https://user-images.githubusercontent.com/69951650/91717731-a30ee080-ebc4-11ea-8874-06ec3c9980a9.png)
> This is what I get after the debug.

This seems to me still the results from "Run". Using "Debug" will automatically open the "Debug" panel not the "Run" panel. Also, debug can provide more information.

**Comment by alexbingqi** [comment]
![image](https://user-images.githubusercontent.com/69951650/91752576-1fbbb200-ebf9-11ea-94c6-8a88b12ffaa7.png)
This is what I get after pressing the debug button.

**Comment by jdchoi77** [comment]
@alexbingqi it seems like you forked the course repository and did not setup gradle from scratch.  The error message is saying that your gradle environment is not setup properly, which should have been setup from Quiz 0.

**Comment by alexbingqi** [comment]
Quiz 0 was running successfully before I encountered the GitHub problem. I might accidentally delete some of the components of the Gradle. What should I do to fix the problem?

**Comment by lujiaying** [comment]
One way is using Github to restore the correct version of Gradle files. Another way is following the instruction to check the differences.

**Comment by marvinquiet** [comment]
Hi, I went through the procedure and I could run it without any problems. If you want, could you please come back to my office hour again so that we can discuss about it?
