### ISSUE TITLE
[QZ#1] Grading

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#24]
Will quiz 1 be graded solely based on if they passed the tests or will you be looking at the code structure as well?Is there a specific code structure design you are looking for or are we just graded based on functionality?

**Comment by jdchoi77** [comment]
@Shreya3554 the grading of Quiz 1 will not be solely on the unit test results. Also, please be aware that unit tests used for the assessment of the quiz can be different from the ones posted in GitHub.
