### ISSUE TITLE
Question About Sign Member Field in Chapter 1.1

### ISSUE THREAD

**Issue by iamechi** [emory-courses/dsa-java#25]
In chapter 1, the flipSign method in SignedNumeral interface was defined as sign = (sign == sign.POSITIVE)? Sign.NEGATIVE: Sign.POSITIVE. However, the text said it would cause a compile error since sign is a constant that couldn't have it's value reassigned.   Was that because the value for the object sign was instantiated as final in the enum class for Sign or because  the sign field was instantiated in an interface version of SignedNumeral?

**Comment by jdchoi77** [comment]
@iamechi it is because the field was defined under the interface version of `SingedNumeral`.  Once we define `SingedNumeral` as `abstract class`, this should not be an issue.

**Comment by iamechi** [comment]
Ok. Thank you.
