### ISSUE TITLE
[QZ1] Starting the Quiz 1

### ISSUE THREAD

**Issue by MimiOlayeye** [emory-courses/dsa-java#26]
We haven't covered all the material yet in class, but if we want to begin quiz 1, should we start by copying the code for Numeral.java, SignedNumeral.java, and LongInteger.java into a new package on IntelliJ?

**Comment by lujiaying** [comment]
Yes, please follow the notebook and explore it if wanna start. Merely copy and paste might not work for some functions.

**Comment by jdchoi77** [comment]
@MimiOlayeye as i mentioned in the class, copy & paste is never encouraged in this course so please try to follow the steps yourself.
