### ISSUE TITLE
[QZ1] Downloading from GitHub

### ISSUE THREAD

**Issue by MimiOlayeye** [emory-courses/dsa-java#28]
For the testing Excersise for Quiz 1, it states that we should download LongIntergerQuizTest.java. 

How do we download directly from Git Hub?

**Comment by marvinquiet** [comment]
Hi, you can go to the repo and then find the [file](https://github.com/emory-courses/dsa-java/blob/master/src/test/java/edu/emory/cs/algebraic/LongIntegerQuizTest.java). 

Then click the `raw` button, it will lead you to the [code](https://raw.githubusercontent.com/emory-courses/dsa-java/master/src/test/java/edu/emory/cs/algebraic/LongIntegerQuizTest.java).

You can choose to either create your own class named LongIntegerQuizTest and paste the content in, or you can try a fancy  way to use a command line `wget https://raw.githubusercontent.com/emory-courses/dsa-java/master/src/test/java/edu/emory/cs/algebraic/LongIntegerQuizTest.java` to get it. 

Please let me know if any questions.

**Comment by MimiOlayeye** [comment]
Thanks!!
