### ISSUE TITLE
[QZ0] Git on Windows / Solution for "Please tell me who you are"

### ISSUE THREAD

**Issue by ananthupucha** [emory-courses/dsa-java#3]
For Windows users who don't have Git installed, you can download it here:
https://git-scm.com/download/win

If the following error comes up, uun the commands below in the IntelliJ terminal and then commit and push.

```
Successfully created project 'dsa-java' on GitHub, but initial commit failed:
*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

**Comment by lujiaying** [comment]
According to the log you provide, it seems that github setup need the information of your account information. 

Could you try to use the window terminal, and execute the above commands under its instruction?

**Comment by ananthupucha** [comment]
I did. I posted this for others who might run into the same problem.

**Comment by jdchoi77** [comment]
@ananthupucha thank you very much posting; I'm adding this content to the book chapter.

**Comment by lujiaying** [comment]
> I did. I posted this for others who might run into the same problem.

Great. Thank you for sharing!

**Comment by jdchoi77** [comment]
This is now added to the book chapter:
https://emory.gitbook.io/dsa-java/getting-started/environment-setup#git-windows-only

**Comment by liamsgordon** [comment]
@jdchoi77 I am having this issue on mac, do I need to connect my email to git?

**Comment by lujiaying** [comment]
> For Windows users who don't have Git installed, you can download it here:
> https://git-scm.com/download/win
> 
> If the following error comes up, uun the commands below in the IntelliJ terminal and then commit and push.
> 
> ```
> Successfully created project 'dsa-java' on GitHub, but initial commit failed:
> *** Please tell me who you are.
> 
> Run
> 
> git config --global user.email "you@example.com"
> git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> ```

@liamsgordon please follow the similar process to set up your GitHub account. Otherwise, git cant not push your local repo into remote repo.
