### ISSUE TITLE
[QZ1] compareAbs method

### ISSUE THREAD

**Issue by schun99** [emory-courses/dsa-java#31]
When using this method, am I supposed to get a negative integer if |_digits_| > |_n.digits_| or |_n.digits_| > |_digits_|?
I think it should be the former according to javadoc, but I get the latter. (ex: from test2 (digits = 123, n.digits = -0) i get a positive integer 2)

**Comment by marvinquiet** [comment]
```
/**
     * @param n the object to be compared.
     * @return a negative integer, zero, or a positive integer as the absolute value of this object is
     * less than, equal to, or greater than the absolute value of the specified object.
     */
    public int compareAbs(LongInteger n) {
        int diff = digits.length - n.digits.length;

        if (diff == 0) {
            for (int i = digits.length - 1; i >= 0; i--) {
                diff = digits[i] - n.digits[i];
                if (diff != 0) break;
            }
        }

        return diff;
    }
```

According to the code here, the digits.length is the length of digits (123), which is 3, and the length of n.digits (-0), is 1. Thus the diff here would be 2.  

Sorry, my first intuition on reading this comment was wrong. After reading this carefully, `this object` refers to the __digits__, and `the specified object` refers to __n__.

**Comment by schun99** [comment]
Thank you!!
