### ISSUE TITLE
[QZ#1] Leading 0s

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#32]
After implementing my method for addDifferentSigns, I get the correct numbers and signs for the tests, however I still have the extra 0s in front of the answer. I tried using a similar idea to the addSameSign method to remove the leading 0s, but I can't get it to work. Is this the right approach to remove the extra 0s for this method?

**Comment by marvinquiet** [comment]
Yeah, you need to remove the leading 0s in your final answer. 

I am not sure if adding the same sign involves the leading 0 problem. But for eliminating the leading 0s, you can just consider removing the several leading items in the vector or counting how many 0s there are, and return it without 0s
