### ISSUE TITLE
[QZ1] Helper Methods

### ISSUE THREAD

**Issue by MimiOlayeye** [emory-courses/dsa-java#33]
Can we create additional helper methods within the LongIntegerQuiz class to use in the addDifferentSign method?

**Comment by marvinquiet** [comment]
Thank you for your question. However, I did not quite understand why would you need to add another helper for this? What is this helper function for?

**Comment by MimiOlayeye** [comment]
I wanted to make a helper method that finds the digit array with the largest number. I realized that my code works best when subtracting the number with the smaller magnitude from the number with the larger magnitude.

**Comment by MimiOlayeye** [comment]
Actually realized I could just use the compareAbs method from the parent class.
