### ISSUE TITLE
[QZ#1] Grading Criteria clarification.

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#35]
I hope everyone is doing well! I'm working on Quiz 1 right now and just wanted to clarify the grading criteria. I tend to get a bit paranoid when it comes to stuff like this so if you don't mind, I'm going to run through my understanding of what is required of us. We cannot copy-paste the code on Github. Is this because that would be considered plagiarism or is that because Dr. Choi wants us to know how the code works? I'm writing the code now but since I'm basing it off the lecture the code is going to end up similar to Dr. Choi's. Sorry if this sounds a bit pedantic--just being careful. My understanding was that this code was made public for us to learn from, so using it would be allowed.

**Comment by marvinquiet** [comment]
I just consulted Dr. Choi and he said that it would be okay to use the code in the coursebook or Github.

**Comment by JonathanKimchi** [comment]
Thank you!
