### ISSUE TITLE
[QZ1] warnings in code

### ISSUE THREAD

**Issue by brendacano** [emory-courses/dsa-java#38]
My code works fine however I have some warnings (shown in the image). Would these affect my grade negatively for quiz 1? They don't seem like a big deal to me but I want to be sure. 
![2020-09-12](https://user-images.githubusercontent.com/69967655/93008097-00008400-f53f-11ea-9392-eedeed632434.png)

**Comment by lujiaying** [comment]
According to https://emory.gitbook.io/dsa-java/java-essentials/exercises

> Override the addDifferentSign() method so that the add() method in LongIntegerQuiz can handle integers with different signs.

Not sure if you implemented several constructor functions. But as long as your codes pass our test cases, warnings would not impact grades.

**Comment by brendacano** [comment]
> According to https://emory.gitbook.io/dsa-java/java-essentials/exercises
> 
> > Override the addDifferentSign() method so that the add() method in LongIntegerQuiz can handle integers with different signs.
> 
> Not sure if you implemented several constructor functions. But as long as your codes pass our test cases, warnings would not impact grades.

Thank you, all the tests were passed with my code.
