### ISSUE TITLE
[QZ#2 Getting started with logic] 

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#39]
I have been attempting to understand the logic of a ternary heap before I get started trying to code. I think a good logic would be parent node at (x - 1)/3 and children at (x * 3) + 1,2,3 for each child. Although I think this logic is solid, I have had some problems translating it into a heap logic. I have thought of two possible scenarios of heap logic and was wondering if any of them sound viable? Logic #1) Each parent and its children are an array of size 4 with the parent first followed by the children, and when that is full a new array is created with one of the children as the 1st node in a new array. Logic #2) Each head element is not part of an array, but the children comprise an array of size 3 for each head. Any feedback on the logic would be greatly appreciated!

**Comment by marvinquiet** [comment]
In my understanding, the ternary heap is similar to the binary one according to chapter 2.2

Sorry I did not quite understand your logic about the implementing this ternary heap, but it seems that once you feel clear about the index of parent, index of left/middle/right child, you are all good to implement this heap. Just think about what you need to do to make this a balanced ternary tree would be helpful.

**Comment by marvinquiet** [comment]
Here is the test logic for the TernaryHeap: [PriorityQueueTest.java](https://github.com/emory-courses/dsa-java/blob/master/src/test/java/edu/emory/cs/queue/PriorityQueueTest.java). 

```
/**
     * @param pq   a priority queue.
     * @param keys a list of comparable keys.
     * @param comp a comparator used for sorting.
     */
    <T extends Comparable<T>> void testRobustnessAux(AbstractPriorityQueue<T> pq, List<T> keys, Comparator<T> comp) {
        keys.forEach(pq::add);
        keys = keys.stream().sorted(comp).collect(Collectors.toList());
        keys.forEach(key -> assertEquals(key, pq.remove()));
    }
```

I just came to think about testing add that you may want to print out the elements `pq` after adding to the heap. But I think in the end, it still needs an expected result in mind to test for the implementation.
