### ISSUE TITLE
[QZ1] 

### ISSUE THREAD

**Issue by TaymarJoseph** [emory-courses/dsa-java#41]
I get errors from the import statements in the LongIntegerQuizTest method after copying and pasting it into IntelliJ.

![Screen Shot 2020-09-14 at 11 59 43 AM](https://user-images.githubusercontent.com/70547554/93109223-c8e6bb80-f681-11ea-9e5b-23cfa19161fc.png)

**Comment by marvinquiet** [comment]
This test file should be under the test folder, not the main folder.

**Comment by TaymarJoseph** [comment]
Thanks
