### ISSUE TITLE
[QZ2] Inputting vararg parameters in IntelliJ

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#42]
Hi everyone! I have a quick question regarding benchmarking in Quiz 2. I am not sure how I can input BinaryHeap and TernaryHeapQuiz as vararg parameters when using the testRobustnessAux() method. I would really appreciate it if someone could explain to me how it works in IntelliJ. Thx!

**Comment by marvinquiet** [comment]
```
@Test
    public void testRobustness() {
        List<Integer> keys = List.of(4, 1, 3, 2, 5, 6, 8, 3, 4, 7, 5, 9, 7);
        Comparator<Integer> natural = Comparator.naturalOrder();
        Comparator<Integer> reverse = Comparator.reverseOrder();

        testRobustnessAux(new TernaryHeapQuiz<>(), keys, reverse);
        testRobustnessAux(new TernaryHeapQuiz<>(reverse), keys, natural);
    }
```

According to the code here, it passes the object into the function.
