### ISSUE TITLE
[QZ#2 Coding requirement] 

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#44]
Can we modify the code we have written for the binary heap class for the quiz, or should we be implementing all of the methods from scratch for the ternary heap?

**Comment by lujiaying** [comment]
The information from https://emory.gitbook.io/dsa-java/priority-queues/exercises might be helpful.

> Create a class called TernaryHeapQuiz under the main queue package that **extends** the abstract class `AbstractPriorityQueue`.
> Feel free to use the code in `BinaryHeap`.
