### ISSUE TITLE
[QZ#2] How is add function in the BinaryHeap nlog(2)n? 

### ISSUE THREAD

**Issue by Shreya3554** [emory-courses/dsa-java#45]
Replace `#` in the title with the appropriate quiz number.
I am not understanding how the add function in the BinaryHeap code that was provided to us is nlog(2)n? If we're just adding a node at the end and then swimming it up, it should just be log(2)n not nlog(2)n. This also applies similarly to the ternary heap-shouldn't the add function be log(3)n not nlog(3)n?

**Comment by lujiaying** [comment]
A brief answer for 
> I am not understanding how the add function in the BinaryHeap code that was provided to us is nlog(2)n? If we're just adding a node at the end and then swimming it up, it should just be log(2)n not nlog(2)n.

According to the first paragraph in https://emory.gitbook.io/dsa-java/priority-queues/binary-heaps#add-with-swim,

> A binary heap is a PQ that takes for both add() and remove()

So, you are correct. The time complexity is `o(log_2(n))`

**Comment by Shreya3554** [comment]
So then how come for the ternary heap assignment, why are we told to make it O(nlog(3)n) when it should be O(log(3)n)?

**Comment by lujiaying** [comment]
I might speculate it as a typo. To my understanding, sort a heap would lead to `O(n log(n))`. Add() and remove() is only `O(log (n))`
