### ISSUE TITLE
[QZ# 2] Heap Correctness Question

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#46]
So my code passes the testrobustnessaux test for both natural and reverse order, but I am still unsure of its correctness. Instead of pasting my code here, I have provided a pictorial representation of the natural and reverse heap that my code generated. I was wondering if these are correct? The array values are the numbers in the circles and their indexes are the numbers in the top left corner of the numbers in the circle.
![IMG_1511](https://user-images.githubusercontent.com/69921592/93712649-30d74f00-fb25-11ea-8d2d-652608fce7eb.jpg)

**Comment by jdchoi77** [comment]
The logic looks correct; you may want to check more on the edge cases.
