### ISSUE TITLE
[QZ#2] Is it alright if we have custom implementations for the helper/auxiliary methods?

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#47]
For example, are we allowed to rewrite the compare function so that it returns something like the index of the larger leaf or create another addon compare function that is able to compare three nodes at once?

**Comment by marvinquiet** [comment]
Hi, 
I will be only extracing out your TernaryHeapQuiz class for testing, thus any other modifications in other places would not be tested and may fail the test cases.
