### ISSUE TITLE
"Timeout waiting to lock journal cache"

### ISSUE THREAD

**Issue by skhardi** [emory-courses/dsa-java#48]
<img width="1019" alt="Screen Shot 2020-09-21 at 9 10 08 PM" src="https://user-images.githubusercontent.com/66644687/93838954-f8349400-fc50-11ea-8e6b-a21e8f980494.png">
Started getting this message today. Can't build or run anything now... Any known solutions or ideas to attempt?

**Comment by marvinquiet** [comment]
According to this, it seems you are running gradle elsewhere. If possible, could you please try `gradle --stop` in the command line and see if it works?

If still not working, try restarting your computer.
