### ISSUE TITLE
[QZ0] 

### ISSUE THREAD

**Issue by iamechi** [emory-courses/dsa-java#5]
I have a question about installing Git. I already have Git installed on my computer, but I have 3 different git applications that were installed: GIT Bash, GIT CMD, and GIT GUI. Are any of these the ones that we are going to be using for class?

**Comment by lujiaying** [comment]
I think all three applications are good to use. And specifically in this class, we would use the integrated version control function inside IntelliJ. 
So in general, we would not need to explicitly choose git application.

**Comment by jdchoi77** [comment]
@iamechi we would not use any git app you listed above. As long as you have git installed on your machine, you are good to go.
