### ISSUE TITLE
[QZ#2] Errors

### ISSUE THREAD

**Issue by ddalama** [emory-courses/dsa-java#50]
Hello,

The 2 images below show the errors I get upon running TernaryHeapQuizTest. Below them, I have attached a picture of my TernaryHeapQuiz class. I would appreciate it if you could help me figure out the issues. 

Also, how can I know if my add() and remove() methods are O(log3n)?

Thank you.

<img width="1440" alt="Err1" src="https://user-images.githubusercontent.com/70519965/93932002-298a8e00-fd3d-11ea-8eb0-d4ebc8a546ec.png">
<img width="1121" alt="Err2" src="https://user-images.githubusercontent.com/70519965/93932006-2c857e80-fd3d-11ea-902c-1f441f3d6436.png">
<img width="1440" alt="prog1" src="https://user-images.githubusercontent.com/70519965/93932432-d1a05700-fd3d-11ea-8a2e-5f29bde38b27.png">

**Comment by lujiaying** [comment]
From the attached picture, the error may come from L46.

Imaging when `k=2`, `compare(k/3, k)` would be `compare(0, 2)`. Since the 0th element in `keys` is `null`, it would raise `NullPointException`.

**Comment by ddalama** [comment]
Thanks for the feedback. In L46, I changed `compare(k/3, k)` to `compare((k+1)/3, k)`, but I got new errors. 

I also changed L38 to `else if((k-1)%3==0 || k%3==0) {` and changed L43 to `else if((k+1)%3==0) { //if node is the left node`

Also, is the problem/error only in swim() method? I can rewrite it if this is the case.

I have attached my errors and new code below:

<img width="1440" alt="Screenshot 2020-09-23 at 4 30 10 AM" src="https://user-images.githubusercontent.com/70519965/93946017-c9ecac80-fd55-11ea-8508-dfb2f45a1f85.png">
![Screenshot 2020-09-23 at 4 31 11 AM](https://user-images.githubusercontent.com/70519965/93946020-cc4f0680-fd55-11ea-91c0-211a04cd1569.png)

**Comment by ddalama** [comment]
Also, is there a way to do the benchmarking part of the assignment if these errors don't go away?

Thanks.

**Comment by jdchoi77** [comment]
@ddalama the NPE is caused because you do not check the key index being 0, which returns `null`.  Make sure it will not access the 0'th key that is `null` in your case.

**Comment by jdchoi77** [comment]
@ddalama please do not post your code as an issue; if you need to please put the link to the code in your private repository. Closing this issue.
