### ISSUE TITLE
[QZ3] Question Regarding class SortTest

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#53]
Hello everyone. When I tried to create the filed final InputNature nature = InputNature.RANDOM, I kept getting errors that said "Cannot resolve symbol 'InputNature'". Does anyone have any idea why this could happen?

**Comment by lujiaying** [comment]
I find a reference of `class InputNature`. It is in https://github.com/emory-courses/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/InputNature.java#L19:13.

Could you try to add the class file under the same package to solve the issue?

**Comment by jdchoi77** [comment]
@HallOfSam please check the import path of `InputNature` as @lujiaying suggested.
