### ISSUE TITLE
[QZ#3] MSD Radix Sort Lamba Expression

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#56]
Is there a way to implement the method by calling the sort() auxiliary method from BucketSort, which includes a lambda expression to define the key? I have been trying to implement it this way, however I can't update div correctly. Is this because the lambda expression must be final? Should we be defining a new BucketSort auxiliary method without the lambda expression?

**Comment by jdchoi77** [comment]
You do not need to call the auxiliary `sort()` method from `BucketSort` for MSDRadixSort if that's easier to implement.
