### ISSUE TITLE
[QZ#3]  Testing parameters

### ISSUE THREAD

**Issue by MimiOlayeye** [emory-courses/dsa-java#57]
For SortTest.java  what does the "..." mean in the testRuntime() method parameter.

The parameter in the method is: **"AbstractSort< Integer >... engines"** and I've never seen that before.

**Comment by chenda2000** [comment]
It's what the @SafeVarargs flag is referring to, basically it lets you pass in as many or as little AbstractSort<Integer> objects as you want (and they're stored in an array, which is why can pass 'engines' directly to the benchmark method)
