### ISSUE TITLE
[QZ#3] Bucket Sort Function.

### ISSUE THREAD

**Issue by MimiOlayeye** [emory-courses/dsa-java#58]
Lambda expressions and functions are still a bit new to me. Can you please help me understand the 'bucketIndex' function in the sort () method of the BucketSort class?

I know it is a function that takes a comparable key, and returns the appropriate index but how does that work?

**Comment by lujiaying** [comment]
Good question.

```Java
@Override
public void sort(Integer[] array, int beginIndex, int endIndex) {
    sort(array, beginIndex, endIndex, key -> key - MIN);
}
```

We know that `key -> key - MIN` is the lambda function that acts as the 'bucketIndex' function. 

In `key -> key - MIN`, the input argument is `key`, and return value is `key - MIN`.
So assuming `MIN` is assigned as `3` in the construction function (imaging the array needs to be sort is `[3,4,10,...]`), then the return values for this lambda function are:
- 3 -> 3-3=0
- 4 -> 4-3=1
- 10 -> 10-3=7
- ...

**Comment by jdchoi77** [comment]
@MimiOlayeye in addition, it can handle negative integers as well.  If `MIN = -3`:

```
-3 - (-3) -> 0
-1 - (-3) -> 1
```
