### ISSUE TITLE
[HW#1] Input Clarification

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#60]
The homework says the input can:

- Contain an arbitrary number of rows, where the size of each row is also arbitrary.

Does this mean you can have jagged 2D arrays(where one row is of length 100 and the next is of length 10), or that every row length is equal to each other but the row length itself is variable?

**Comment by jdchoi77** [comment]
> Does this mean you can have jagged 2D arrays (where one row is of length 100 and the next is of length 10)
Yes
