### ISSUE TITLE
Java Version Compatibility 

### ISSUE THREAD

**Issue by superfastjellyfish001** [emory-courses/dsa-java#62]
I encountered the following issue when I try to run the code. I suspect it is caused by java version incompatibility, but I'm not sure.

Could you help me look at it? Thank you!

<img width="1263" alt="Screen Shot 2020-09-28 at 9 15 27 PM" src="https://user-images.githubusercontent.com/60992582/94437109-e4001200-01cf-11eb-94bc-783571bfeef5.png">

**Comment by lujiaying** [comment]
It may be caused by version incompatibility, or caused by some runtime errors. Zero exit value is typically considered as successful execution. I would suggest trying `debug` instead of `run` to see more logs.

**Comment by Abner3** [comment]
I would reinstall java and make sure the IntelliJ settings are all correct according to Chapter 0 in the textbook.
