### ISSUE TITLE
[QZ#3] are the quiz all gonna be this hard 

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/dsa-java#67]
I just have a quick question about whether all the coming quizzes are gonna be as hard as this one. It took me two whole days to finish it, so Im just wondering if theres a typical expected time we should normally spend on these?

**Comment by marvinquiet** [comment]
I think I can not answer this question from my own experience. But perhaps Dr. Choi @jdchoi77 can have some comments on this..
