### ISSUE TITLE
[QZ#3] Negative inputs?

### ISSUE THREAD

**Issue by chenda2000** [emory-courses/dsa-java#68]
The testRobustness method given only generates random positive integers. While I'm pretty sure any of the shellsorts can handle them, I was wondering if our MSD radix sort is supposed to be able to handle negative integers?

**Comment by marvinquiet** [comment]
You are asking a very good question! I will ask Dr. Choi and let you know

**Comment by lujiaying** [comment]
For MSD, no negative integers would be considered (not imply to any other sorting).
