### ISSUE TITLE
[QZ#3] Code assistance

### ISSUE THREAD

**Issue by superfastjellyfish001** [emory-courses/dsa-java#70]
I really struggled to track down the error in my recursive method, and I'm not sure if it's on the right track. Could you help me look at it?
Thanks a lot!

https://github.com/superfastjellyfish001/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/distribution/RadixSortQuiz.java

**Comment by marvinquiet** [comment]
Hi, for a first glance, I did not see any return statements in your recursive. Please think about adding that condition when it enters a situation that you do not need to sort it.
