### ISSUE TITLE
[HW#1] Grading

### ISSUE THREAD

**Issue by lcunild** [emory-courses/dsa-java#71]
Will there be a grading rubric for homework 1?

**Comment by marvinquiet** [comment]
Sorry, I am not sure yet. But I think the basic requirements should be met, i.e. speed-up

**Comment by lcunild** [comment]
Will we get any credit if our program is not faster? I have tried writing lots of different solutions however even though they work, none of them are quicker than the baseline.

**Comment by lujiaying** [comment]
Just get an update that Dr. Choi will talk about it in Monday's class.
