### ISSUE TITLE
[QZ3] Gradle Testing Issue

### ISSUE THREAD

**Issue by LukHan99** [emory-courses/dsa-java#73]
I encountered an issue that each time when I tried to run the testrobustness() method in the SortQuizTest class. the testing does not end and always ask me the same following sentence:

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] 

and no matter whether I answer yes or no, the testing will end and turns out to be passed. However, I was unsure if that means my codes for the RadixSortQuiz() and ShellSortQuiz() are working or not. I also want to know what caused this message to pop up each time and how to get rid of it. Thanks!
  
<img width="1378" alt="Screen Shot 2020-10-02 at 06 42 13" src="https://user-images.githubusercontent.com/69959537/94870577-6f043500-047a-11eb-882e-b0dddac9b89d.png">

**Comment by lujiaying** [comment]
It seems that you are trying to creating build scans. Is that what you want?

Otherwise, maybe try right click on the test file and only `debug` or `run` it.

**Comment by LukHan99** [comment]
I might have clicked something related to build scans unintentionally when debugging, so are there any ways to fix this issue other than just running the whole test file?

**Comment by lujiaying** [comment]
Yes, it is possible to run only one test function.

Please refer to the tutorial:
https://www.jetbrains.com/help/idea/performing-tests.html
