### ISSUE TITLE
[HW1] 

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#75]
Hello! I have a question regarding HybridSortTest. I keep getting errors that suggest that my input type for testRobustness() and testRunTime() is wrong because it is not an AbstractSort type (I think it's because the interface HybridSort does not inherit AbstractSort). 

How should I implement HybridSortHW and adjust HybridSortBaseline so that they can be tested? Or should I override the testing methods? Thanks in advance.

**Comment by lujiaying** [comment]
It seems that you have figured it out, right? @HallOfSam

**Comment by HallOfSam** [comment]
Yes! Thank you so much!
