### ISSUE TITLE
[QZ3] fail to pass the robustness test

### ISSUE THREAD

**Issue by Lokakaaa** [emory-courses/dsa-java#76]
Replace `#` in the title with the appropriate quiz number.
I have tested my code using different datasets and they all went well, and I can also print out the array generated by the robustness test in a sorted order(using print array added by myself). However, I cannot pass the robustness test. Can you please help me find if anything is wrong?
![image](https://user-images.githubusercontent.com/69859833/94997065-2f089380-05db-11eb-85a2-c732d8081610.png)

 Here is the link to my code
https://github.com/Lokakaaa/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/distribution/RadixSortQuiz.java
Thank you so much.

**Comment by lujiaying** [comment]
https://github.com/Lokakaaa/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/distribution/RadixSortQuiz.java#L9

`cum` is not reset to zero after sort one input array. That means in the next invoked sort(), cum is not `0` and may lead to unexpected errors.

**Comment by Lokakaaa** [comment]
I designed "cum" not to be reset to 0. For example, after I sorted all the numbers between 0-100, I will add new counts based on cum to reach the array 100-199.
By the way, I am really confused since when I add print array in my code, it gives the sorted array, but I cannot pass the robustness test. Like this:
![image](https://user-images.githubusercontent.com/69859833/94998881-c542b680-05e7-11eb-9234-ecda32e773cf.png)

**Comment by lujiaying** [comment]
```Java
    void testRobustness(AbstractSort<Integer> engine) {
        final int iter = 100;
        final int size = 1000;
        final Random rand = new Random();
        Integer[] original, sorted;

        for (int i = 0; i < iter; i++) {
            original = Stream.generate(() -> rand.nextInt(size)).limit(size).toArray(Integer[]::new);
            sorted = Arrays.copyOf(original, size);

            engine.sort(original);
            Arrays.sort(sorted);
            assertArrayEquals(original, sorted);
        }
    }
```

`engine` would be tested with multiple arrays.  I highly doubt errors are introduced due to that `cum` not be reset.

**Comment by lujiaying** [comment]
> I have tested my code using different datasets and they all went well,

I tested your codes, it succeeded for one input array. However, not able to deal with multiple arrays need to be tested.

**Comment by Lokakaaa** [comment]
You are right, my problem is solved. Thank you so much!

> > I have tested my code using different datasets and they all went well,
> 
> I tested your codes, it succeeded for one input array. However, not able to deal with multiple arrays need to be tested.
