### ISSUE TITLE
[QZ#3] How to test Radix sort quiz

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#80]
I am not sure which method/ file we are supposed to use to test radix sort, when I use test robustness within sortquiztest, even the method Dr. Choi made does not pass the testrobustness test

**Comment by TFloyd1989** [comment]
Specifically , LSDradixsort does not pass the testrobustness, and neither does my radixsortquiz

**Comment by TFloyd1989** [comment]
This is what I get when I try to test LSDsort
![Screenshot (26)](https://user-images.githubusercontent.com/69921592/95026596-6ff6bb80-0660-11eb-90f7-1be15e50301e.png)

**Comment by marvinquiet** [comment]
Hi, I checked Dr. Choi's code and it worked for me. Please make sure you did not change anything from Dr. Choi's repo.

![image](https://user-images.githubusercontent.com/7233574/95027245-0b8a2b00-0665-11eb-9e25-d8ccb2cb731a.png)

**Comment by TFloyd1989** [comment]
I made sure that they were exact copies(sorttest and sortquiztest) and testrobustness still does not work for any of the tests in sorttest

**Comment by TFloyd1989** [comment]
Also, I notice in your code base that MSDradixsort does not throw an error, in our class we were never instructed to create that file

**Comment by marvinquiet** [comment]
I was creating this for testing other students' code because he wrote it under MSDRadixSort. Are you sure you also copied the correct LSDRadixSort? If possible, could you please push what you have to the Github and send me a link so that I can have a look at it.

**Comment by TFloyd1989** [comment]
https://github.com/TFloyd1989/dsa-javaTFII
I've pushed everything

**Comment by TFloyd1989** [comment]
Within sorttest, I commented out the other tests and figured out that even selection sort failed the testrobustness

**Comment by marvinquiet** [comment]
Hi, I copied your code and run in my IDE, it successfully worked. 

My suggestion would be restarting IDE because sometimes it may have some weird errors. Please also make sure that you run the correct testRobustness:

![image](https://user-images.githubusercontent.com/7233574/95027993-d08af600-066a-11eb-91b6-f93ba15f764d.png)

**Comment by TFloyd1989** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/69921592/95028054-80606380-066b-11eb-8f02-e834d685948c.png)
I restarted my ide and I still got the same error. I am becoming increasingly worried because I think I may have gotten the radixsortquiz right, but I am unable to test it due to this error

**Comment by TFloyd1989** [comment]
Do you have any recommendations to fix this? I'm very passionate about this course, but I'm just not sure how to get around this issue. I would hate to fail a quiz I could do but just couldn't test

**Comment by lujiaying** [comment]
Hi @TFloyd1989,  please allow non-immediate response since it is on weekend not on weekdays.  As TA, we are not expected to actively respond during weekend.

Back to the issue, I would suggest to keep your own implementations , and to delete all files that are copied from the textbook. Then re-do the copy process.   

From the comment

> Hi, I copied your code and run in my IDE, it successfully worked.
> 
> My suggestion would be restarting IDE because sometimes it may have some weird errors. Please also make sure that you run the correct testRobustness:
> 
> ![image](https://user-images.githubusercontent.com/7233574/95027993-d08af600-066a-11eb-91b6-f93ba15f764d.png)

I doubt that some superclass files were accidentally modified.

**Comment by TFloyd1989** [comment]
Thank you for your response, I do appreciate the help given that you are not obligated to respond. However, I have deleted and recopied the files multiple times, as well as updating my IDE and I'm still getting the same errors

**Comment by TFloyd1989** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/69921592/95029501-c7a02180-0676-11eb-82db-b439dc1d9136.png)
The specific problem is that the code in line 50 ( engine.sort(original);) does not invoke the sort method from the engine type. Instead, it does nothing, resulting in an unchanged array

**Comment by TFloyd1989** [comment]
*line 54

**Comment by marvinquiet** [comment]
Hi, I cloned your repo and found the same error. And after replacing your script "BucketSort" and "RadixSort" with Dr. Choi's script, it could run.

So, please calm down and make sure that you copied all files correctly.

**Comment by TFloyd1989** [comment]
Thank you for helping me solve these problems. I apologize for any inconvenience caused by my persistence in trying to get this problem solved, that's just how important this class is to me. I hope you both have a great rest of your weekend!

**Comment by lujiaying** [comment]
@TFloyd1989 thank you for putting efforts in this class. Hope you can learn a lot from it because algorithm is definitely one of the core concepts in computer science.  And maybe the most useful one since it would be extremely examined during interviews.
