### ISSUE TITLE
[HW1] Question Regarding How HybridSortHW Will Be Tested

### ISSUE THREAD

**Issue by HallOfSam** [emory-courses/dsa-java#82]
For HW1, is it true that the class HybridSortHW will be tested independent of our own packages and everything should be done within that class? Or can we create new classes in the packages that can be used by HybridSortHW ? Thanks in advance.

**Comment by marvinquiet** [comment]
It will be tested independently. So please do not add other files.

**Comment by lcunild** [comment]
If we want to optimise the other sorting algorithms we have done in class, can we write a new class within our HW class to use in our implementation? Or are we only allowed to use the sorting classes we have already created in the previous classes/quizzes?

**Comment by marvinquiet** [comment]
That is a very good question. I suggest you directly asking Dr. Choi during the class.
