### ISSUE TITLE
[QZ#3] Recursion help

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#84]
I feel that I am in the final steps of this quiz, I have the preliminary sort done, and now I just need to recursively sort through the subarrays. I was wondering if I could get a little bit of help figuring it out?
![Screenshot (31)](https://user-images.githubusercontent.com/69921592/95068201-f8ae3f80-06d2-11eb-9dd7-5e0ed9c0b83b.png)

**Comment by marvinquiet** [comment]
Hi, I think this question is directly related to the solution to the problem so I cannot give a detailed solution to you. But just consider utilizing the beginIndx and endIndex to find the return statement of the recursion and sort them accordingly.
