### ISSUE TITLE
[QZ#3] What each column in the output corresponds to.

### ISSUE THREAD

**Issue by JonathanKimchi** [emory-courses/dsa-java#85]
I'm currently writing up the documentation for our quiz runtime. Just wanna make sure I'm getting this correct since the columns don't have any labels. Left to right, what are the bars supposed to represent? I know the first two columns represent the random sorting case since that number is clearly distinct, but I'm not sure which bar is the ascending and descending case since the data is much more similar. Some clarification would be greatly appreciated. Thank you!
Sincerely,

**Comment by marvinquiet** [comment]
Sorry for the late reply. You can read it from the SortTest.java which could give you some hints. I think this question is also directly related to the answer of the problem.
