### ISSUE TITLE
[HW1] Due Date 

### ISSUE THREAD

**Issue by brendacano** [emory-courses/dsa-java#90]
If I turn in my code for the extra credit on Wednesday do I still have the opportunity to turn it in again by Friday if I figure out a faster hybrid sort?

**Comment by JonathanKimchi** [comment]
I second this question.

**Comment by marvinquiet** [comment]
Please directly consult Dr. Choi about late submission and grading.

**Comment by brendacano** [comment]
> Please directly consult Dr. Choi about late submission and grading.

Should I email him?

**Comment by marvinquiet** [comment]
Or you can ask about it during his office hour or class.
