### ISSUE TITLE
[HW#1] HybridSortBaseline

### ISSUE THREAD

**Issue by guylikekai** [emory-courses/dsa-java#92]
I wanted to test out the HybridSortBaseline code on the example array given in the homework assignment, but when I run the robustness test (line 44 & line 62-72) it says that the test failed because the arrays differed at the first element. Did I write the unit test incorrectly?

https://github.com/guylikekai/dsa-java/blob/master/src/test/java/edu/emory/cs/sort/SortTest.java 

Update: I printed out the result of using HybridSortBaseline on the array and it is not sorted correctly. I tried deleting HybridSortBaseline and directly copying the code from the professor's github doc but the same thing happens. Am I missing something?

https://github.com/guylikekai/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/hybrid/HybridSortBaseline.java

**Comment by lujiaying** [comment]
I think `HybridSortBaseline` should work perfectly without failing in any test cases if codes are copied correctly.

**Comment by guylikekai** [comment]
Turns out there was an error in my shell sort! Thank you very much!
