### ISSUE TITLE
[HW1] Must subarrays sizes be the same? LSDRadixSort?

### ISSUE THREAD

**Issue by HowardYutingHou** [emory-courses/dsa-java#93]
I have two questions
1. Can the subarrays have different sizes, or must their sizes be the same?
2. Are we expected to use LSDRadixSort, as it could theoretically boost the running speed?

**Comment by HowardYutingHou** [comment]
Sorry, just noticed that the hw pages says the sizes can vary. How about LSDRadixSort?

**Comment by marvinquiet** [comment]
Yes, you can use the code you wrote or code provided by the course as long as it is faster

**Comment by HowardYutingHou** [comment]
I have a problem using LSDRadixSort, as it defines generic type to be Integer, while HybridSortHW takes T. So, I get an error when using LSDRadixSort in HybridSortHW. Could you give a hint how to deal with it?

**Comment by JonathanKimchi** [comment]
I believe since HybridSortHW takes T, you cannot use LSDRadixSort since there is no way to define the bounds of the buckets.

**Comment by lujiaying** [comment]
> I have a problem using LSDRadixSort, as it defines generic type to be Integer, while HybridSortHW takes T. So, I get an error when using LSDRadixSort in HybridSortHW. Could you give a hint how to deal with it?

Please notice that, if using LSDRadixSort, it might lead to failure when dealing with negative integers. Also, As @JonathanKimchi mentioned, it can not pass compile phase due to `<T>`.

**Comment by jdchoi77** [comment]
@HowardYutingHou currently, LDSRadixSoft assumes integer but the input can be any comparable keys in this homework  so it may not always work.
