### ISSUE TITLE
Oct7 Wednesday lecture recording 

### ISSUE THREAD

**Issue by caroltang0331** [emory-courses/dsa-java#94]
The 10/7 Tries link on schedule page on Github lead me to an error page. Im wondering if its just me or there's something wrong with the recording link ? Thank you

**Comment by lujiaying** [comment]
The recording of 10/7 lecture might not been uploaded yet. I can not open the link too

**Comment by jdchoi77** [comment]
@caroltang0331  thanks for letting me know; i thought it had been pushed but it wasn't. It is not updated on the course wepbage and the link is here: https://emory.zoom.us/rec/share/AR6PtqaiDN4hQfSYXwrbThtQdIR0Fd-A26VdwDlXJmRCNmt-8jKO_nZ5GgjH6Gw.__gUSUYvMThYDZ88
